//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BSCTestT
    {
        public int OperationType { get; set; }
        public string OperationName { get; set; }
        public Nullable<long> OpAmt { get; set; }
        public string OpDescriptin { get; set; }
        public string AddedColumn { get; set; }
        public Nullable<int> AddedColumn2 { get; set; }
        public string AddedColumn3 { get; set; }
        public string AddedColumn4 { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> OperationId { get; set; }
        public int ID { get; set; }
    }
}
