//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashLocationGroupTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CashLocationGroupTable()
        {
            this.CashLocationTables = new HashSet<CashLocationTable>();
            this.CashLocationGroupTable1 = new HashSet<CashLocationGroupTable>();
        }
    
        public int CashLocationGroupID { get; set; }
        public string CashLocationGroupKey { get; set; }
        public string CashLocationGroupName { get; set; }
        public string CashLocationGroupNote { get; set; }
        public Nullable<int> CashLocationGroupParentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashLocationTable> CashLocationTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CashLocationGroupTable> CashLocationGroupTable1 { get; set; }
        public virtual CashLocationGroupTable CashLocationGroupTable2 { get; set; }
    }
}
