//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashLiveSupplierEdit2
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public int ShellDataPageLinkID { get; set; }
        public int ShellDataPageLineLinkID { get; set; }
        public Nullable<int> StockSupplierID_CR { get; set; }
        public Nullable<double> IncomingBAmount { get; set; }
        public Nullable<double> OutstandingInvoiceAmount { get; set; }
        public Nullable<double> OutstandingPaymentAmount { get; set; }
        public Nullable<double> IncomingEAmount { get; set; }
        public Nullable<double> Total_IncomingBAmount { get; set; }
        public Nullable<double> Total_OutstandingInvoiceAmount { get; set; }
        public Nullable<double> Total_OutstandingPaymentAmount { get; set; }
        public Nullable<double> Total_IncomingEamount { get; set; }
        public Nullable<int> StockEntryTypeID2_C { get; set; }
    }
}
