//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashWorkLiveTable
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID { get; set; }
        public int ShellMessageID { get; set; }
        public Nullable<System.DateTime> ShellDateFrom { get; set; }
        public Nullable<System.DateTime> ShellDateTo { get; set; }
        public Nullable<int> CashLocationID { get; set; }
        public Nullable<int> CashLocationGroupID { get; set; }
        public Nullable<int> CashItemGroupID { get; set; }
        public Nullable<int> CashCompanyID { get; set; }
        public Nullable<int> CashCompanyGroupID { get; set; }
        public Nullable<int> CashItemID { get; set; }
        public Nullable<double> CashAmount { get; set; }
        public Nullable<System.DateTime> CashEntryDate { get; set; }
        public Nullable<int> CashEntryID { get; set; }
        public Nullable<int> CashEntryLineSortID { get; set; }
        public Nullable<int> CashEntryTypeID { get; set; }
        public string CashEntryKey { get; set; }
        public string CashEntryName { get; set; }
        public Nullable<long> CashEntryLineID { get; set; }
        public Nullable<int> CashEntryLineTypeID { get; set; }
        public Nullable<int> ShellYesNo { get; set; }
        public Nullable<int> ShellYesNo1 { get; set; }
        public Nullable<int> ShellYesNo2 { get; set; }
        public Nullable<int> ShellYesNo3 { get; set; }
        public Nullable<int> ShellYesNo4 { get; set; }
        public Nullable<int> ShellYesNo5 { get; set; }
        public Nullable<int> ShellWorkPageParentID { get; set; }
        public Nullable<int> ShellWorkPageLineParentID { get; set; }
        public Nullable<int> CashEntryStatusID { get; set; }
        public Nullable<double> CashAmount2 { get; set; }
        public Nullable<double> CashAmount3 { get; set; }
        public Nullable<double> CashAmount4 { get; set; }
        public Nullable<int> CashUserID { get; set; }
        public Nullable<int> CashPersonID { get; set; }
        public Nullable<int> StockEntryTypeID2 { get; set; }
        public Nullable<System.DateTime> StockEntryDate { get; set; }
    }
}
