//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashLiveCustomerEdit1
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public int ShellDataPageLinkID { get; set; }
        public int ShellDataPageLineLinkID { get; set; }
        public Nullable<int> StockCustomerID_CR { get; set; }
        public Nullable<double> OutstandingBAmount { get; set; }
        public Nullable<double> OutstandingInvoiceAmount { get; set; }
        public Nullable<double> OutstandingPaymentAmount { get; set; }
        public Nullable<double> OutstandingEAmount { get; set; }
        public Nullable<double> Total_OutstandingBAmount { get; set; }
        public Nullable<double> Total_OutstandingInvoiceAmount { get; set; }
        public Nullable<double> Total_OutstandingPaymentAmount { get; set; }
        public Nullable<double> Total_OutstandingEAmount { get; set; }
        public Nullable<System.DateTime> LastStockEntryDate { get; set; }
        public Nullable<System.DateTime> LastCashEntryDate { get; set; }
    }
}
