//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashLocationGroupEdit5
    {
        public int CashLocationID { get; set; }
        public string CashLocationKey { get; set; }
        public string CashLocationName { get; set; }
        public int CashLocationTypeID_C { get; set; }
        public int CashLocationGroupID { get; set; }
    }
}
