//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashEntryI10Edit0
    {
        public long ShellWorkID { get; set; }
        public int ShellMessageID_R { get; set; }
        public int ShellWorkStatusID_B { get; set; }
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public Nullable<int> CashEntryID { get; set; }
        public Nullable<System.DateTime> StockEntryDate { get; set; }
        public string CashEntryKey { get; set; }
        public string CashEntryName { get; set; }
        public Nullable<int> cmdNextRow { get; set; }
        public Nullable<int> CashLocationID_C { get; set; }
    }
}
