//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashLiveEntry00Edit1
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellMessageID { get; set; }
        public int ShellDataPageLinkID { get; set; }
        public int ShellDataPageLineLinkID { get; set; }
        public Nullable<int> CashEntryID { get; set; }
        public Nullable<int> CashEntryTypeID_CR { get; set; }
        public Nullable<int> CashEntryStatusID_CR { get; set; }
        public string CashEntryKey { get; set; }
        public string CashEntryName { get; set; }
        public int ShellUserID_CR { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public Nullable<System.DateTime> StockEntryDate { get; set; }
        public Nullable<int> CashLocationID_CR { get; set; }
    }
}
