//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashWorkTable
    {
        public long ShellWorkID { get; set; }
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID { get; set; }
        public Nullable<int> ShellWorkPageParentID { get; set; }
        public string ShellWorkPageLineParentID { get; set; }
        public double ShellWorkPageSign { get; set; }
        public int ShellWorkPageAuto { get; set; }
        public int ShellMessageID { get; set; }
        public int ShellWorkStatusID { get; set; }
        public Nullable<int> CashEntrySortID { get; set; }
        public Nullable<int> CashEntryID { get; set; }
        public Nullable<long> CashEntryLineID { get; set; }
        public string CashEntryKey { get; set; }
        public string CashEntryName { get; set; }
        public Nullable<System.DateTime> CashEntryDate { get; set; }
        public Nullable<int> CashEntryTypeID { get; set; }
        public Nullable<int> CashEntryStatusID { get; set; }
        public double CashEntrySign { get; set; }
        public Nullable<int> CashEntryParentID { get; set; }
        public Nullable<long> CashEntryLineParentID { get; set; }
        public Nullable<int> CashLocationID { get; set; }
        public Nullable<int> CashLocationID2 { get; set; }
        public Nullable<int> CashCompanyID { get; set; }
        public int CashItemID { get; set; }
        public double CashAmount { get; set; }
        public Nullable<System.DateTime> ShellCreationDate { get; set; }
        public Nullable<System.DateTime> ShellModificationDate { get; set; }
        public Nullable<int> ShellCreatorUserID { get; set; }
        public Nullable<int> ShellModifierUserID { get; set; }
        public Nullable<int> ShellAcceptorUserID { get; set; }
        public Nullable<int> ShellRejectorUserID { get; set; }
        public Nullable<int> ShellRejectorUserID1 { get; set; }
        public Nullable<int> ShellRejectorUserID2 { get; set; }
        public Nullable<int> ShellRejectorUserID3 { get; set; }
        public Nullable<int> ShellRejectorUserID4 { get; set; }
        public Nullable<int> ShellRejectorUserID5 { get; set; }
        public Nullable<int> ShellRejectorUserID6 { get; set; }
        public Nullable<int> ShellRejectorUserID7 { get; set; }
        public Nullable<int> ShellRejectorUserID8 { get; set; }
        public Nullable<int> CashPersonID { get; set; }
    }
}
