//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashEntry00Edit1
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellMessageID_R { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public Nullable<System.DateTime> StockEntryDate { get; set; }
        public Nullable<int> StockCustomerID_C { get; set; }
        public double CashAmount { get; set; }
        public Nullable<int> StockPersonID_C { get; set; }
        public string CashEntryName { get; set; }
    }
}
