//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportPOSUserTable
    {
        public int ShellUserID { get; set; }
        public string ShellUserKey { get; set; }
        public string ShellUserName { get; set; }
        public int ShellUserSortID { get; set; }
        public int ShellUserTypeID { get; set; }
        public int ShellUserStatusID { get; set; }
        public int ShellUserGroupID { get; set; }
        public string ShellUserPassword { get; set; }
        public int ShellLanguageID { get; set; }
        public string ShellServerKey { get; set; }
    }
}
