//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportPOSComputerTable
    {
        public int ShellComputerID { get; set; }
        public string ShellComputerKey { get; set; }
        public string ShellComputerName { get; set; }
        public int ShellComputerSortID { get; set; }
        public int ShellComputerTypeID { get; set; }
        public int ShellComputerStatusID { get; set; }
        public int ShellComputerGroupID { get; set; }
        public int StockLocationID { get; set; }
        public Nullable<int> StockCustomerID { get; set; }
        public string ShellServerKey { get; set; }
    }
}
