//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportPOSLocationTable
    {
        public int StockLocationID { get; set; }
        public string StockLocationKey { get; set; }
        public string StockLocationName { get; set; }
        public int StockLocationSortID { get; set; }
        public int StockLocationTypeID { get; set; }
        public int StockLocationStatusID { get; set; }
        public int StockLocationGroupID { get; set; }
        public string ShellServerKey { get; set; }
    }
}
