//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportRPOSPeriodTable
    {
        public int StockPayPeriodID { get; set; }
        public string StockPayPeriodKey { get; set; }
        public string StockPayPeriodName { get; set; }
        public Nullable<System.DateTime> StockPayPeriodValidFrom { get; set; }
        public Nullable<System.DateTime> StockPayPeriodValidTo { get; set; }
        public int StockPayPeriodStatusID { get; set; }
        public Nullable<int> StockLocationID { get; set; }
        public Nullable<int> StockCustomerID { get; set; }
        public int ShellComputerID { get; set; }
        public int ShellUserID { get; set; }
        public Nullable<System.DateTime> ShellSyncDate { get; set; }
    }
}
