//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportRPOSEntryLineTable
    {
        public int ExportRPOSEntryID { get; set; }
        public long ExportRPOSEntryLineID { get; set; }
        public int ExportRPOSEntryID2 { get; set; }
        public long ExportRPOSEntryLineID2 { get; set; }
        public int StockEntryLineSortID { get; set; }
        public int StockEntryLineTypeID { get; set; }
        public int StockEntryLineStatusID { get; set; }
        public long ExportRPOSEntryLineParentID { get; set; }
        public long ExportRPOSEntryLineParentID2 { get; set; }
        public System.DateTime StockEntryLineDate { get; set; }
        public string StockEntryLineKey { get; set; }
        public string StockEntryLineName { get; set; }
        public int StockLocationID { get; set; }
        public int StockItemID { get; set; }
        public int StockItemUnitID { get; set; }
        public double StockQuantity { get; set; }
        public double StockAmount { get; set; }
        public int StockItemID2 { get; set; }
        public int TransItemUnitID { get; set; }
        public double TransPriceAmount { get; set; }
        public Nullable<double> TransTaxBaseFactor { get; set; }
        public double TransTaxFactor { get; set; }
        public double TransTotalAmount { get; set; }
        public System.DateTime TransDate { get; set; }
        public double StockTaxBaseAmount { get; set; }
        public double StockTaxAmount { get; set; }
        public double StockTotalAmount { get; set; }
        public double CommisionPercent { get; set; }
        public int StockLocationID2 { get; set; }
        public decimal StockItemNWeight { get; set; }
        public decimal StockItemGWeight { get; set; }
        public int StockItemID3 { get; set; }
        public int StockBOMPlanLineTypeID { get; set; }
        public decimal Quantity2 { get; set; }
        public int TransItemID { get; set; }
        public double TransItemUnitFactor { get; set; }
        public double TransQuantityInitial { get; set; }
        public double TransQuantity { get; set; }
        public int TransQuantityAllowChange { get; set; }
        public double TransPriceInitial { get; set; }
        public double TransPrice { get; set; }
        public int TransPriceAllowChange { get; set; }
        public double TransPriceOverall { get; set; }
        public int TransPriceDiscount { get; set; }
        public double TransPriceDiscountFactor { get; set; }
        public double TransPriceDiscountAmount { get; set; }
        public int TransTaxID { get; set; }
        public double TransTaxBaseAmount { get; set; }
        public double TransTaxAmount { get; set; }
        public int StockLocationShelfID { get; set; }
        public System.DateTime StockEntryLineDate2 { get; set; }
        public int ShellFlag { get; set; }
        public int ShellFlag1 { get; set; }
        public int ShellFlag2 { get; set; }
        public int ShellFlag3 { get; set; }
        public int ShellFlag4 { get; set; }
        public int ShellFlag5 { get; set; }
        public int ShellFlag6 { get; set; }
        public int ShellFlag7 { get; set; }
        public int TransPayMethodID { get; set; }
        public int TransSortID { get; set; }
        public int StockCostCodeID { get; set; }
        public int StockUserID { get; set; }
        public int ShellSyncProcessID { get; set; }
        public System.DateTime ShellSyncDate { get; set; }
        public int StockTaxBaseAmount2 { get; set; }
        public int StockTaxAmount2 { get; set; }
        public int StockTotalAmount2 { get; set; }
    }
}
