//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExportPOSCompanyTable
    {
        public int StockCompanyID { get; set; }
        public string StockCompanyKey { get; set; }
        public string StockCompanyName { get; set; }
        public int StockCompanySortID { get; set; }
        public int StockCompanyTypeID { get; set; }
        public int StockCompanyStatusID { get; set; }
        public int StockCompanyGroupID { get; set; }
        public string StockCompanyAddress { get; set; }
        public string StockCompanyPhone { get; set; }
        public string StockCompanyMail { get; set; }
        public string StockCompanyWeb { get; set; }
        public int TaxCodeID { get; set; }
        public int StockTaxMethodID { get; set; }
        public double StockCompanyDiscountFactor { get; set; }
        public string ShellServerKey { get; set; }
        public Nullable<int> StockLocationID { get; set; }
    }
}
