//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportRPOSItemGroupTable
    {
        public int StockItemGroupID { get; set; }
        public string StockItemGroupKey { get; set; }
        public string StockItemGroupName { get; set; }
        public int StockItemGroupParentID { get; set; }
        public int StockItemGroupSortID { get; set; }
    }
}
