//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportPOSEntryTable
    {
        public int ExportPOSEntryID { get; set; }
        public int ExportPOSEntryID2 { get; set; }
        public int ExportPOSEntryParentID2 { get; set; }
        public int ExportPOSEntryParentID { get; set; }
        public string StockEntryKey { get; set; }
        public string StockEntryName { get; set; }
        public int StockEntrySortID { get; set; }
        public int StockEntryTypeID { get; set; }
        public int StockEntryStatusID { get; set; }
        public System.DateTime StockEntryDate { get; set; }
        public System.DateTime StockEntryDateInitial { get; set; }
        public int StockLocationID { get; set; }
        public int StockLocationID2 { get; set; }
        public int TransCompanyID { get; set; }
        public int TransCompanyCardID { get; set; }
        public int TransTaxMethodID { get; set; }
        public double TransTaxMethodFactor { get; set; }
        public double TransAmount { get; set; }
        public double TransTaxAmount { get; set; }
        public double TransBaseAmount { get; set; }
        public int TransDiscountID { get; set; }
        public double TransDiscountFactor { get; set; }
        public double TransDiscountAmount { get; set; }
        public double TransDiscountTaxAmount { get; set; }
        public double TransDiscountBaseAmount { get; set; }
        public double TransTotalAmount { get; set; }
        public double TransTotalTaxAmount { get; set; }
        public double TransTotalBaseAmount { get; set; }
        public double TransTotalPayAmount { get; set; }
        public int TransPayPeriodID { get; set; }
        public int TransPayMethodID { get; set; }
        public double TransPayCashAmount { get; set; }
        public double TransPayCashChangeAmount { get; set; }
        public double TransPayBankAmount { get; set; }
        public double TransPayInvoiceAmount { get; set; }
        public double TransPayOtherAmount { get; set; }
        public int ShellUserID { get; set; }
        public int ShellComputerID { get; set; }
        public int ShellCustomerID { get; set; }
        public System.DateTime ShellSyncDate { get; set; }
        public int ShellSyncProcessID { get; set; }
    }
}
