//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportRPOSCompanyTable
    {
        public int StockCompanyID { get; set; }
        public string StockCompanyKey { get; set; }
        public string StockCompanyName { get; set; }
        public string StockCompanyName_EN { get; set; }
        public int StockCompanyTypeID { get; set; }
        public int StockCompanyStatusID { get; set; }
        public int StockCompanyGroupID { get; set; }
        public Nullable<int> StockPriceID { get; set; }
        public string StockCompanyCountry { get; set; }
        public string StockCompanyAddress { get; set; }
        public string StockCompanyAddress2 { get; set; }
        public string StockCompanyAddress3 { get; set; }
        public string StockCompanyPhone { get; set; }
        public string StockCompanyFax { get; set; }
        public string StockCompanyMail { get; set; }
        public string StockCompanyWeb { get; set; }
        public string StockCompanyTaxNumber { get; set; }
        public int TaxCodeID { get; set; }
        public string StockCompanyBankCode { get; set; }
        public string StockCompanyBankName { get; set; }
        public string StockCompanyBankAccount { get; set; }
        public Nullable<int> StockCompanyParentID { get; set; }
        public int StockCompanyFlag { get; set; }
        public int StockTaxMethodID { get; set; }
        public double StockCompanyDiscountFactor { get; set; }
        public int StockZSortID { get; set; }
    }
}
