//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportRPOSSalesItemPriceTable
    {
        public long StockPriceLineID { get; set; }
        public string StockPriceLineKey { get; set; }
        public string StockPriceLineName { get; set; }
        public int StockPriceLineSortID { get; set; }
        public int StockPriceLineSortID2 { get; set; }
        public Nullable<int> StockPriceLineTypeID { get; set; }
        public int StockPriceLineStatusID { get; set; }
        public int StockPriceID { get; set; }
        public int StockItemID { get; set; }
        public int StockItemID2 { get; set; }
        public int StockPriceItemUnitID { get; set; }
        public double StockPriceItemUnitFactor { get; set; }
        public double FCPrice { get; set; }
        public int CurrencyID { get; set; }
        public int TaxCodeID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public double CommisionPercent { get; set; }
        public double AllocationPercent { get; set; }
        public int StockAllowChange { get; set; }
        public System.DateTime ShellCreationDate { get; set; }
        public Nullable<System.DateTime> ShellModificationDate { get; set; }
        public System.DateTime StockPriceLineValidFrom { get; set; }
        public double StockBasePrice { get; set; }
        public double StockBasePriceFactor { get; set; }
        public Nullable<System.DateTime> StockPriceLineValidTo { get; set; }
        public Nullable<int> StockEntryID { get; set; }
        public Nullable<int> StockLocationID { get; set; }
        public int StockSalesItemGroupID { get; set; }
    }
}
