//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportRPOSCarGroupTable
    {
        public int StockCarGroupID { get; set; }
        public string StockCarGroupKey { get; set; }
        public string StockCarGroupName { get; set; }
        public Nullable<int> StockCarGroupParentID { get; set; }
    }
}
