//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportRPOSCompanyGroupTable
    {
        public int StockCompanyGroupID { get; set; }
        public string StockCompanyGroupKey { get; set; }
        public string StockCompanyGroupName { get; set; }
        public Nullable<int> StockCompanyGroupParentID { get; set; }
    }
}
