//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImportRPOSLocationTable
    {
        public int StockLocationID { get; set; }
        public string StockLocationKey { get; set; }
        public string StockLocationName { get; set; }
        public string StockLocationName_EN { get; set; }
        public int StockLocationTypeID { get; set; }
        public int StockLocationStatusID { get; set; }
        public Nullable<System.DateTime> StockLocationValidFrom { get; set; }
        public Nullable<System.DateTime> StockLocationValidTo { get; set; }
        public int StockLocationGroupID { get; set; }
        public string StockLocationAddress { get; set; }
        public Nullable<int> PersonID { get; set; }
        public Nullable<int> PersonID2 { get; set; }
        public Nullable<int> PersonID3 { get; set; }
        public Nullable<int> StockCustomerID { get; set; }
        public Nullable<int> StockLocationID2 { get; set; }
        public string ExactCostCenter { get; set; }
        public string StockPrinterName { get; set; }
    }
}
