//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutstandingEntryTable
    {
        public int OutstandingEntryID { get; set; }
        public string OutstandingEntryKey { get; set; }
        public string OutstandingEntryName { get; set; }
        public System.DateTime OutstandingEntryDate { get; set; }
        public int OutstandingEntryTypeID { get; set; }
        public int OutStandingEntryStatusID { get; set; }
        public int OutstandingCompanyID { get; set; }
        public Nullable<double> OutstandingAmount { get; set; }
        public double OutstandingInvoiceAmount { get; set; }
        public Nullable<double> OutstandingPaymentAmount { get; set; }
        public int OutstandingEntryTypeID2 { get; set; }
        public Nullable<System.DateTime> StockEntryDate { get; set; }
        public Nullable<System.DateTime> CashEntryDate { get; set; }
    }
}
