//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSinTouch_ProductsList
    {
        public int ID { get; set; }
        public string Barcode { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public int CategoryID { get; set; }
    }
}
