//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POSinTouch_Z
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellMessageID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int StockEntryID { get; set; }
        public System.DateTime StockEntryDate { get; set; }
        public string StockEntryKey { get; set; }
        public string StockEntryName { get; set; }
        public int TransCompanyID { get; set; }
        public double TransAmount { get; set; }
        public double TransServiceAmount { get; set; }
        public double TransDiscountAmount { get; set; }
        public double TransTotalAmount { get; set; }
        public double TransTotalTaxAmount { get; set; }
        public double TransTotalBaseAmount { get; set; }
        public double TransPayCashAmount { get; set; }
        public double TransPayCashChangeAmount { get; set; }
        public double TransPayBankAmount { get; set; }
        public double TransPayInvoiceAmount { get; set; }
        public double TransPayOtherAmount { get; set; }
        public double StockPayPeriodOpenAmount { get; set; }
        public double StockPayPeriodCashAmount { get; set; }
        public double StockPayPeriodInAmount { get; set; }
        public double StockPayPeriodOutAmount { get; set; }
        public double StockPayPeriodDifferenceAmount { get; set; }
        public double StockPayPeriodCloseAmount { get; set; }
        public int ShellWorkStatusID { get; set; }
    }
}
