//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSEntryWP10Edit0
    {
        public int ShellMessageID_R { get; set; }
        public int ShellWorkStatusID { get; set; }
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public Nullable<int> StockEntryID { get; set; }
        public Nullable<System.DateTime> ShellDateFrom { get; set; }
        public Nullable<System.DateTime> ShellDateTo { get; set; }
        public string RsCompanyKEY { get; set; }
        public string RsCompanyNAME { get; set; }
        public string RsWaybillKEY { get; set; }
        public string RsEndAddress { get; set; }
        public Nullable<int> RSWaybillTypeID_A { get; set; }
        public string RsPersonNAME { get; set; }
        public string RsTransportKEY { get; set; }
    }
}
