//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSEntryATable
    {
        public int RSEntryAID { get; set; }
        public string RSEntryAKey { get; set; }
        public string RSEntryAName { get; set; }
        public int RSEntryAGroupID { get; set; }
        public int RSEntryATypeID { get; set; }
        public int RSEntryAStatusID { get; set; }
        public int StockCompanyID { get; set; }
        public System.DateTime StockEntryDate { get; set; }
        public int StockEntryID2 { get; set; }
        public int RSMessageID { get; set; }
        public long RSWaybillID { get; set; }
        public string RSWaybillKey { get; set; }
        public int StockLocationID { get; set; }
        public int ShellComputerID { get; set; }
        public int StockPayPeriodID { get; set; }
        public double FullAmount { get; set; }
        public int RSSyncProcessID { get; set; }
    }
}
