//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSEntryAEdit0
    {
        public int RSEntryAID { get; set; }
        public string RSEntryAKey { get; set; }
        public int RSEntryAGroupID { get; set; }
        public int RSEntryATypeID { get; set; }
        public int RSEntryAStatusID { get; set; }
        public int StockEntryID2 { get; set; }
        public int StockPayPeriodID_R { get; set; }
        public System.DateTime ShellDateTime_R { get; set; }
        public int StockCompanyID_C { get; set; }
        public string RSEntryAName { get; set; }
        public double FullAmount_R { get; set; }
        public int RSMessageID_CR { get; set; }
    }
}
