//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSEntryWP10Edit2
    {
        public int ShellMessageID_R { get; set; }
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public Nullable<int> ShellWorkPageParentID { get; set; }
        public string ShellWorkPageLineParentID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public string RsCompanyKEY_R { get; set; }
        public string RsCompanyNAME_R { get; set; }
        public string RsWaybillKEY_R { get; set; }
        public string RsItemKey { get; set; }
        public string RSItemName { get; set; }
        public string RSUnitNAME { get; set; }
        public Nullable<double> RSQuantity { get; set; }
        public Nullable<double> RSPrice { get; set; }
        public Nullable<int> RSTaxID_excise { get; set; }
        public Nullable<int> RSTaxID_VAT { get; set; }
        public Nullable<double> RSAmount { get; set; }
        public Nullable<int> cmdnextcolumn { get; set; }
        public Nullable<int> StockItemT0ID_C { get; set; }
        public Nullable<int> StockItemUnitID_C { get; set; }
        public Nullable<double> StockItemUnitFactor { get; set; }
        public Nullable<double> StockPrice { get; set; }
        public Nullable<double> StockTaxID_C { get; set; }
        public Nullable<int> StockPriceLineTypeID_C { get; set; }
        public Nullable<int> StockMarkupGroupID_AR { get; set; }
    }
}
