//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSEntryWP10Edit1
    {
        public int ShellMessageID_R { get; set; }
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public string RsEndAddress_R { get; set; }
        public Nullable<int> StockLocationID_C { get; set; }
        public string RsCompanyKey_R { get; set; }
        public string RsCompanyNAME_R { get; set; }
        public string RsWaybillKey_R { get; set; }
        public Nullable<int> RsWaybillStatusID_R { get; set; }
        public Nullable<int> RsConfirmationStatusID_R { get; set; }
        public Nullable<int> RSCorrectionStatusID_R { get; set; }
        public Nullable<System.DateTime> RsActivateDate { get; set; }
        public Nullable<double> RSAmount { get; set; }
        public string RSWaybillName { get; set; }
        public string StockEntryName { get; set; }
        public Nullable<int> RsWaybillTypeID_CR { get; set; }
    }
}
