//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSLogTable
    {
        public long RSLogID { get; set; }
        public System.DateTime RSLogDate { get; set; }
        public string RSLogKey { get; set; }
        public string RSLogName { get; set; }
        public int SyncProcessID { get; set; }
    }
}
