//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSMessageTable
    {
        public int RSMessageID { get; set; }
        public string RSMessageKEY { get; set; }
        public string RSMessageNAME { get; set; }
        public string RSMessageNOTE { get; set; }
        public int RSMessageTypeID { get; set; }
        public int RSMessageStatusID { get; set; }
        public System.DateTime RSMessageValidFROM { get; set; }
        public System.DateTime RSMessageValidTO { get; set; }
        public int RSMessageSORT { get; set; }
        public int RSMessageGroupID { get; set; }
    
        public virtual RSMessageGroupTable RSMessageGroupTable { get; set; }
        public virtual RSMessageStatusTable RSMessageStatusTable { get; set; }
        public virtual RSMessageTypeTable RSMessageTypeTable { get; set; }
    }
}
