//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RsWaybillConfirmationStatusTable
    {
        public int RsWaybillConfirmationStatusID { get; set; }
        public string RsWaybillConfirmationStatusKEY { get; set; }
        public string RsWaybillConfirmationStatusNAME { get; set; }
        public string RsWaybillConfirmationStatusNOTE { get; set; }
    }
}
