//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RsWaybillTable
    {
        public long RSWaybillID { get; set; }
        public string RSWaybillKEY { get; set; }
        public string RSWaybillName { get; set; }
        public Nullable<int> RsWaybillTypeID { get; set; }
        public Nullable<int> RsWaybillStatusID { get; set; }
        public string RsMyCompanyKEY { get; set; }
        public string RsMyCompanyNAME { get; set; }
        public string RsCompanyKEY { get; set; }
        public string RsCompanyNAME { get; set; }
        public string RsStartAddress { get; set; }
        public string RsEndAddress { get; set; }
        public Nullable<System.DateTime> RsCreateDate { get; set; }
        public Nullable<System.DateTime> RsDeliveriDate { get; set; }
        public Nullable<System.DateTime> RsActivateDate { get; set; }
        public Nullable<System.DateTime> RsCloseDate { get; set; }
        public Nullable<System.DateTime> RsBeginDate { get; set; }
        public Nullable<int> RsConfirmationStatusID { get; set; }
        public string RsPersonKEY { get; set; }
        public string RsPersonNAME { get; set; }
        public string RsTransportKEY { get; set; }
        public Nullable<double> RSAmount { get; set; }
        public Nullable<int> StockSupplierID { get; set; }
        public Nullable<int> StockCustomerID { get; set; }
        public Nullable<int> StockLocationID { get; set; }
        public Nullable<int> StockPersonID { get; set; }
        public Nullable<int> StockCarID { get; set; }
        public Nullable<int> StockEntryID { get; set; }
        public Nullable<int> ShellMessageID { get; set; }
        public int ShellProcessID { get; set; }
        public Nullable<double> StockAmount { get; set; }
        public Nullable<double> StockTaxAmount { get; set; }
        public Nullable<double> StockBaseAmount { get; set; }
        public int RSCorrectionStatusID { get; set; }
        public System.DateTime ShellCreated { get; set; }
        public System.DateTime ShellUpdated { get; set; }
        public Nullable<double> TransAmount { get; set; }
        public Nullable<double> TransTaxAmount { get; set; }
        public Nullable<double> TransBaseAmount { get; set; }
        public string StockEntryName { get; set; }
    }
}
