//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSWaybillTable_Part
    {
        public int C_StockEntryID { get; set; }
        public string Comment { get; set; }
        public System.DateTime BEGIN_DATE { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string BUYER_NAME { get; set; }
        public string BUYER_TIN { get; set; }
        public string START_ADDRESS { get; set; }
        public string END_ADDRESS { get; set; }
        public double FULL_AMOUNT { get; set; }
        public Nullable<int> TRAN_COST_PAYER { get; set; }
        public int TYPE { get; set; }
        public Nullable<int> CHEK_BUYER_TIN { get; set; }
        public int Status { get; set; }
        public int ID { get; set; }
        public int C_RSSyncProcessID { get; set; }
        public System.DateTime C_RSSyncDate { get; set; }
        public int C_RSMessageID { get; set; }
        public string DRIVER_NAME { get; set; }
        public string Driver_TIN { get; set; }
        public Nullable<int> TRANS_ID { get; set; }
        public string TRANS_TXT { get; set; }
        public string C_RSWaybillID { get; set; }
        public string CAR_NUMBER { get; set; }
        public string RECEPTION_INFO { get; set; }
        public string RECEIVER_INFO { get; set; }
        public Nullable<int> CHEK_DRIVER_TIN { get; set; }
        public Nullable<int> ACTIVATE_DATE { get; set; }
        public long C_RSWaybillKey { get; set; }
        public Nullable<int> C_RSInvoiceID { get; set; }
    }
}
