//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RsWaybillLineTable
    {
        public long RSWaybillLineID { get; set; }
        public long RSWaybillID { get; set; }
        public int RSWaybillLineStatusID { get; set; }
        public string RSItemKey { get; set; }
        public string RSItemName { get; set; }
        public int RSUnitID { get; set; }
        public string RSUnitName { get; set; }
        public double RSQuantity { get; set; }
        public double RSPrice { get; set; }
        public Nullable<int> RSTaxID { get; set; }
        public Nullable<int> RSTaxID2 { get; set; }
        public double RSAmount { get; set; }
        public Nullable<int> StockItemID { get; set; }
        public Nullable<int> StockItemUnitID { get; set; }
        public Nullable<double> StockItemUnitFactor { get; set; }
        public Nullable<int> StockPriceLineTypeID { get; set; }
        public Nullable<double> StockPrice { get; set; }
        public Nullable<int> StockPriceTaxID { get; set; }
        public Nullable<double> StockPriceTaxFactor { get; set; }
        public Nullable<int> StockEntryID { get; set; }
        public Nullable<long> StockEntryLineID { get; set; }
        public Nullable<int> ShellMessageID { get; set; }
        public int ShellProcessID { get; set; }
        public Nullable<double> StockAmount { get; set; }
        public Nullable<double> StockTaxAmount { get; set; }
        public Nullable<double> StockBaseAmount { get; set; }
        public Nullable<int> StockMarkupGroupID { get; set; }
        public Nullable<int> StockMarkupID { get; set; }
        public Nullable<double> TransPrice { get; set; }
        public Nullable<int> TransTaxID { get; set; }
        public Nullable<double> TransTaxFactor { get; set; }
        public Nullable<double> TransAmount { get; set; }
        public Nullable<double> TransTaxAmount { get; set; }
        public Nullable<double> TransBaseAmount { get; set; }
    }
}
