//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellSessionTable1
    {
        public string ShellDeviceKey { get; set; }
        public string ShellEntityKey { get; set; }
        public string ShellServerKey { get; set; }
        public string ShellInstanceKey { get; set; }
        public string ShellDatabaseKey { get; set; }
        public int ShellDeviceID { get; set; }
        public int ShellLocationID { get; set; }
    }
}
