//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellSyncList
    {
        public int ShellSyncID { get; set; }
        public string ShellSyncKey { get; set; }
        public string ShellSyncName { get; set; }
        public int ShellSyncTypeID { get; set; }
        public int ShellSyncStatusID { get; set; }
        public Nullable<System.DateTime> ShellSyncDateFrom { get; set; }
        public Nullable<System.DateTime> ShellSyncDateTo { get; set; }
        public Nullable<int> ShellSyncProcessID { get; set; }
    }
}
