//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellReportEdit1
    {
        public int ShellReportID { get; set; }
        public int ShellReportFilterID { get; set; }
        public int ShellReportFilterSortID { get; set; }
        public string ShellReportFilterKey { get; set; }
        public string ShellReportFilterName { get; set; }
        public int ShellReportFilterTypeID_B { get; set; }
        public int ShellReportFilterStatusID_B { get; set; }
    }
}
