//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellLogTable
    {
        public long ShellLogID { get; set; }
        public string ShellLogKey { get; set; }
        public string ShellLogName { get; set; }
        public int ShellLogSortID { get; set; }
        public System.DateTime ShellLogDate { get; set; }
        public System.TimeSpan ShellLogTime { get; set; }
        public string ShellLogValue { get; set; }
        public string ShellLogXML { get; set; }
    }
}
