//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellSettingTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShellSettingTable()
        {
            this.ShellSettingValueTables = new HashSet<ShellSettingValueTable>();
        }
    
        public int ShellSettingID { get; set; }
        public string ShellSettingKey { get; set; }
        public string ShellSettingName { get; set; }
        public int ShellSettingTypeID { get; set; }
        public int ShellSettingStatusID { get; set; }
        public int ShellSettingGroupID { get; set; }
        public int ShellSettingSortID { get; set; }
        public string ShellSettingValue { get; set; }
    
        public virtual ShellSettingGroupTable ShellSettingGroupTable { get; set; }
        public virtual ShellSettingStatusTable ShellSettingStatusTable { get; set; }
        public virtual ShellSettingTypeTable ShellSettingTypeTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellSettingValueTable> ShellSettingValueTables { get; set; }
    }
}
