//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellUserTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShellUserTable()
        {
            this.ShellComputerUserTables = new HashSet<ShellComputerUserTable>();
            this.ShellReportFilterValueTables = new HashSet<ShellReportFilterValueTable>();
            this.ShellSettingValueTables = new HashSet<ShellSettingValueTable>();
            this.StockEntryTables = new HashSet<StockEntryTable>();
        }
    
        public int ShellUserID { get; set; }
        public string ShellUserKey { get; set; }
        public string ShellUserName { get; set; }
        public int ShellUserTypeID { get; set; }
        public int ShellUserStatusID { get; set; }
        public System.DateTime ShellUserValidFrom { get; set; }
        public System.DateTime ShellUserValidTo { get; set; }
        public int ShellUserGroupID { get; set; }
        public int ShellUserSortID { get; set; }
        public int ShellLanguageID { get; set; }
        public string ShellUserPassword { get; set; }
        public string ShellUserCard { get; set; }
        public string ShellNTUserName { get; set; }
        public string ShellNTComputerName { get; set; }
        public string ShellLogOnTime { get; set; }
        public string ShellLogOffTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellComputerUserTable> ShellComputerUserTables { get; set; }
        public virtual ShellLanguageTable ShellLanguageTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellReportFilterValueTable> ShellReportFilterValueTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellSettingValueTable> ShellSettingValueTables { get; set; }
        public virtual ShellUserGroupTable ShellUserGroupTable { get; set; }
        public virtual ShellUserStatusTable ShellUserStatusTable { get; set; }
        public virtual ShellUserTypeTable ShellUserTypeTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockEntryTable> StockEntryTables { get; set; }
    }
}
