//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellSchedulerStatusTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShellSchedulerStatusTable()
        {
            this.ShellSchedulerTables = new HashSet<ShellSchedulerTable>();
        }
    
        public int ShellSchedulerStatusID { get; set; }
        public string ShellSchedulerStatusKEY { get; set; }
        public string ShellSchedulerStatusNAME { get; set; }
        public string ShellSchedulerStatusNOTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellSchedulerTable> ShellSchedulerTables { get; set; }
    }
}
