//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellOperationLineTable
    {
        public int ShellOperationID { get; set; }
        public int ShellOperationLineID { get; set; }
        public int ShellEntryLineTypeID { get; set; }
        public int ShellEntryLineStatusID { get; set; }
        public double ShellEntryLineSign { get; set; }
        public int ShellEntryLineAuto { get; set; }
    
        public virtual ShellOperationTable ShellOperationTable { get; set; }
    }
}
