//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellSchedulerTypeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShellSchedulerTypeTable()
        {
            this.ShellSchedulerTables = new HashSet<ShellSchedulerTable>();
        }
    
        public int ShellSchedulerTypeID { get; set; }
        public string ShellSchedulerTypeKEY { get; set; }
        public string ShellSchedulerTypeNAME { get; set; }
        public string ShellSchedulerTypeNOTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellSchedulerTable> ShellSchedulerTables { get; set; }
    }
}
