//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellDiagnoseTypeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShellDiagnoseTypeTable()
        {
            this.ShellDiagnoseTables = new HashSet<ShellDiagnoseTable>();
        }
    
        public int ShellDiagnoseTypeID { get; set; }
        public string ShellDiagnoseTypeKey { get; set; }
        public string ShellDiagnoseTypeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellDiagnoseTable> ShellDiagnoseTables { get; set; }
    }
}
