//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellMessageList
    {
        public int ShellMessageID { get; set; }
        public string ShellMessageKey { get; set; }
        public string ShellMessageName { get; set; }
        public int ShellMessageTypeID { get; set; }
        public int ShellMessageStatusID { get; set; }
        public int ShellMessageGroupID { get; set; }
    }
}
