//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellOperationEdit0
    {
        public int ShellOperationID { get; set; }
        public string ShellOperationKey { get; set; }
        public string ShellOperationName { get; set; }
        public int ShellOperationTypeID_C { get; set; }
        public int ShellOperationStatusID_C { get; set; }
        public int ShellOperationGroupID_H { get; set; }
        public int ShellOperationSortID { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public int ShellEntryTypeID { get; set; }
        public int ShellEntryStatusID { get; set; }
        public int ShellEntryAcceptedStatusID { get; set; }
        public int ShellEntryRejectedStatusID { get; set; }
        public int ShellEntryVoidStatusID { get; set; }
        public int ShellEntryAccessID { get; set; }
        public Nullable<int> cmdNextColumn2 { get; set; }
        public int ShellDataID_C { get; set; }
        public int ShellDataValueTypeID { get; set; }
        public int ShellDataValueStatusID { get; set; }
    }
}
