//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellDataRightTable
    {
        public int ParentDataID { get; set; }
        public int ParentID { get; set; }
        public int ChildDataID { get; set; }
        public int ChildID { get; set; }
    
        public virtual ShellDataTable ShellDataTable { get; set; }
    }
}
