//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellDLLTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShellDLLTable()
        {
            this.ShellDLLLanguageTables = new HashSet<ShellDLLLanguageTable>();
        }
    
        public int ShellDLLID { get; set; }
        public string ShellDLLKEY { get; set; }
        public string ShellDLLPATH { get; set; }
        public string ShellDLLNAME { get; set; }
        public string ShellDLLNOTE { get; set; }
        public int ShellDLLTypeID { get; set; }
        public int ShellDLLStatusID { get; set; }
        public System.DateTime ShellDLLValidFROM { get; set; }
        public System.DateTime ShellDLLValidTO { get; set; }
        public int ShellDLLSORT { get; set; }
        public int ShellDLLGroupID { get; set; }
    
        public virtual ShellDLLGroupTable ShellDLLGroupTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellDLLLanguageTable> ShellDLLLanguageTables { get; set; }
        public virtual ShellDLLStatusTable ShellDLLStatusTable { get; set; }
        public virtual ShellDLLTypeTable ShellDLLTypeTable { get; set; }
    }
}
