//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellDiagnoseGroupTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShellDiagnoseGroupTable()
        {
            this.ShellDiagnoseTables = new HashSet<ShellDiagnoseTable>();
            this.ShellDiagnoseGroupTable1 = new HashSet<ShellDiagnoseGroupTable>();
        }
    
        public int ShellDiagnoseGroupID { get; set; }
        public string ShellDiagnoseGroupKey { get; set; }
        public string ShellDiagnoseGroupName { get; set; }
        public int ShellDiagnoseGroupParentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellDiagnoseTable> ShellDiagnoseTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellDiagnoseGroupTable> ShellDiagnoseGroupTable1 { get; set; }
        public virtual ShellDiagnoseGroupTable ShellDiagnoseGroupTable2 { get; set; }
    }
}
