//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellTermEdit0
    {
        public int ShellTermID { get; set; }
        public string ShellTermKey { get; set; }
        public string ShellTermName { get; set; }
        public int ShellTermTypeID_C { get; set; }
        public int ShellTermStatusID_C { get; set; }
        public int ShellTermGroupID_H { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public string ShellTermFormat { get; set; }
    }
}
