//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellDataSearchTable
    {
        public int ShellDataID { get; set; }
        public int ShellDataSearchID { get; set; }
        public string ShellDataSearchKey { get; set; }
        public string ShellDataSearchName { get; set; }
        public string ShellDataSearchFormat { get; set; }
    
        public virtual ShellDataSearchTable ShellDataSearchTable1 { get; set; }
        public virtual ShellDataSearchTable ShellDataSearchTable2 { get; set; }
        public virtual ShellDataTable ShellDataTable { get; set; }
    }
}
