//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellComputerEdit0
    {
        public int ShellComputerID { get; set; }
        public string ShellComputerKey { get; set; }
        public string ShellComputerName { get; set; }
        public int ShellComputerStatusID_C { get; set; }
        public int ShellComputerTypeID_C { get; set; }
        public int ShellComputerGroupID_C { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public int StockLocationID_CS { get; set; }
    }
}
