//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellOperationGroupTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShellOperationGroupTable()
        {
            this.ShellOperationTables = new HashSet<ShellOperationTable>();
            this.ShellOperationGroupTable1 = new HashSet<ShellOperationGroupTable>();
        }
    
        public int ShellOperationGroupID { get; set; }
        public string ShellOperationGroupKey { get; set; }
        public string ShellOperationGroupName { get; set; }
        public int ShellOperationGroupParentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellOperationTable> ShellOperationTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellOperationGroupTable> ShellOperationGroupTable1 { get; set; }
        public virtual ShellOperationGroupTable ShellOperationGroupTable2 { get; set; }
    }
}
