//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellSettingGroupEdit0
    {
        public int ShellSettingGroupID { get; set; }
        public string ShellSettingGroupKey { get; set; }
        public string ShellSettingGroupName { get; set; }
        public string ShellSettingGroupNote { get; set; }
        public Nullable<int> ShellSettingGroupParentID { get; set; }
    }
}
