//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellDLLGroupTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShellDLLGroupTable()
        {
            this.ShellDLLTables = new HashSet<ShellDLLTable>();
            this.ShellDLLGroupTable1 = new HashSet<ShellDLLGroupTable>();
        }
    
        public int ShellDLLGroupID { get; set; }
        public string ShellDLLGroupKEY { get; set; }
        public string ShellDLLGroupNAME { get; set; }
        public string ShellDLLGroupNOTE { get; set; }
        public int ShellDLLGroupSORT { get; set; }
        public int ShellDLLGroupParentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellDLLTable> ShellDLLTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellDLLGroupTable> ShellDLLGroupTable1 { get; set; }
        public virtual ShellDLLGroupTable ShellDLLGroupTable2 { get; set; }
    }
}
