//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellSessionTable
    {
        public string ShellDeviceKey { get; set; }
        public string ShellEntityKey { get; set; }
        public int ShellDeviceID { get; set; }
        public string ShellDeviceName { get; set; }
        public int ShellLocationID { get; set; }
        public string ShellLocationKey { get; set; }
        public string ShellLocationName { get; set; }
        public int ShellCompanyID { get; set; }
        public string ShellCompanyKey { get; set; }
        public string ShellCompanyName { get; set; }
    }
}
