//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellOperationTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShellOperationTable()
        {
            this.ShellOperationLineTables = new HashSet<ShellOperationLineTable>();
        }
    
        public int ShellOperationID { get; set; }
        public string ShellOperationKey { get; set; }
        public string ShellOperationName { get; set; }
        public int ShellOperationTypeID { get; set; }
        public int ShellOperationStatusID { get; set; }
        public int ShellOperationGroupID { get; set; }
        public int ShellOperationSortID { get; set; }
        public int ShellEntryTypeID { get; set; }
        public int ShellEntryStatusID { get; set; }
        public int ShellEntryAcceptedStatusID { get; set; }
        public int ShellEntryRejectedStatusID { get; set; }
        public int ShellEntryVoidStatusID { get; set; }
        public int ShellEntryAccessID { get; set; }
        public int ShellDataID { get; set; }
        public int ShellDataValueTypeID { get; set; }
        public int ShellDataValueStatusID { get; set; }
    
        public virtual ShellOperationGroupTable ShellOperationGroupTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellOperationLineTable> ShellOperationLineTables { get; set; }
        public virtual ShellOperationStatusTable ShellOperationStatusTable { get; set; }
        public virtual ShellOperationTypeTable ShellOperationTypeTable { get; set; }
    }
}
