//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellReportFilterStatusTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShellReportFilterStatusTable()
        {
            this.ShellReportFilterTables = new HashSet<ShellReportFilterTable>();
        }
    
        public int ShellReportFilterStatusID { get; set; }
        public string ShellReportFilterStatusKey { get; set; }
        public string ShellReportFilterStatusName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellReportFilterTable> ShellReportFilterTables { get; set; }
    }
}
