//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellComputerGroupTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShellComputerGroupTable()
        {
            this.ShellComputerGroupTable1 = new HashSet<ShellComputerGroupTable>();
            this.ShellComputerTables = new HashSet<ShellComputerTable>();
        }
    
        public int ShellComputerGroupID { get; set; }
        public string ShellComputerGroupKey { get; set; }
        public string ShellComputerGroupName { get; set; }
        public int ShellComputerGroupParentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellComputerGroupTable> ShellComputerGroupTable1 { get; set; }
        public virtual ShellComputerGroupTable ShellComputerGroupTable2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellComputerTable> ShellComputerTables { get; set; }
    }
}
