//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellOperationGroupEdit1
    {
        public int ShellOperationID { get; set; }
        public string ShellOperationKey { get; set; }
        public string ShellOperationName { get; set; }
        public int ShellOperationTypeID_A { get; set; }
        public int ShellOperationStatusID_A { get; set; }
        public int ShellOperationGroupID { get; set; }
        public int ShellEntryTypeID { get; set; }
        public int ShellEntryStatusID { get; set; }
        public int ShellEntryAcceptedStatusID { get; set; }
        public int ShellEntryRejectedStatusID { get; set; }
        public int ShellEntryVoidStatusID { get; set; }
        public int ShellEntryAccessID { get; set; }
    }
}
