//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellTermList
    {
        public int ShellTermID { get; set; }
        public string ShellTermKey { get; set; }
        public string ShellTermName { get; set; }
        public int ShellTermTypeID { get; set; }
        public int ShellTermStatusID { get; set; }
        public int ShellTermGroupID { get; set; }
        public string ShellTermFormat { get; set; }
        public string ShellTermGroupKey { get; set; }
        public string ShellTermGroupName { get; set; }
    }
}
