//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellDLLTypeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShellDLLTypeTable()
        {
            this.ShellDLLTables = new HashSet<ShellDLLTable>();
        }
    
        public int ShellDLLTypeID { get; set; }
        public string ShellDLLTypeKEY { get; set; }
        public string ShellDLLTypeNAME { get; set; }
        public string ShellDLLTypeNOTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellDLLTable> ShellDLLTables { get; set; }
    }
}
