//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellWorkPageTable
    {
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkEntryTypeID { get; set; }
        public int ShellWorkEntryStatusID { get; set; }
        public double ShellWorkEntrySign { get; set; }
        public int ShellWorkEntryAuto { get; set; }
    }
}
