//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellDiagnoseGroupEdit5
    {
        public int ShellDiagnoseID { get; set; }
        public string ShellDiagnoseKey { get; set; }
        public string ShellDiagnoseName { get; set; }
        public int ShellDiagnoseTypeID_C { get; set; }
        public int ShellDiagnoseGroupID { get; set; }
    }
}
