//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellDataGroupEdit0
    {
        public int ShellDataGroupID { get; set; }
        public string ShellDataGroupKey { get; set; }
        public string ShellDataGroupName { get; set; }
        public int ShellDataGroupID_C { get; set; }
    }
}
