//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellReportFilterTypeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShellReportFilterTypeTable()
        {
            this.ShellReportFilterTables = new HashSet<ShellReportFilterTable>();
        }
    
        public int ShellReportFilterTypeID { get; set; }
        public string ShellReportFilterTypeKey { get; set; }
        public string ShellReportFilterTypeName { get; set; }
        public string ShellControlKey { get; set; }
        public string SQLType { get; set; }
        public string SQLPrefix { get; set; }
        public string SQLSuffix { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellReportFilterTable> ShellReportFilterTables { get; set; }
    }
}
