//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellTermGroupEdit0
    {
        public int ShellTermGroupID { get; set; }
        public string ShellTermGroupKey { get; set; }
        public string ShellTermGroupName { get; set; }
        public Nullable<int> ShellTermGroupParentID_H { get; set; }
    }
}
