//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellMessageGroupTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShellMessageGroupTable()
        {
            this.ShellMessageGroupTable1 = new HashSet<ShellMessageGroupTable>();
            this.ShellMessageTables = new HashSet<ShellMessageTable>();
        }
    
        public int ShellMessageGroupID { get; set; }
        public string ShellMessageGroupKey { get; set; }
        public string ShellMessageGroupName { get; set; }
        public int ShellMessageGroupParentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellMessageGroupTable> ShellMessageGroupTable1 { get; set; }
        public virtual ShellMessageGroupTable ShellMessageGroupTable2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellMessageTable> ShellMessageTables { get; set; }
    }
}
