//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellUserEdit0
    {
        public int ShellUserID { get; set; }
        public string ShellUserKey { get; set; }
        public string ShellUserName { get; set; }
        public int ShellUserTypeID_C { get; set; }
        public int ShellUserStatusID_C { get; set; }
        public System.DateTime ShellUserValidFrom { get; set; }
        public System.DateTime ShellUserValidTo { get; set; }
        public int ShellUserGroupID_C { get; set; }
        public int ShellLanguageID_C { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public string ShellUserPassword { get; set; }
        public string ShellNTUserName { get; set; }
        public string ShellNTComputerName { get; set; }
        public string ShellLogOnTime { get; set; }
        public string ShellLogOffTime { get; set; }
        public string ShellUserCard { get; set; }
    }
}
