//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellTermNameTable
    {
        public int ShellLanguageID { get; set; }
        public int ShellTermID { get; set; }
        public string ShellTermName { get; set; }
    
        public virtual ShellLanguageTable ShellLanguageTable { get; set; }
        public virtual ShellTermTable ShellTermTable { get; set; }
    }
}
