//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellReportFilterTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ShellReportFilterTable()
        {
            this.ShellReportFilterValueTables = new HashSet<ShellReportFilterValueTable>();
        }
    
        public int ShellReportFilterID { get; set; }
        public int ShellReportFilterSortID { get; set; }
        public string ShellReportFilterKey { get; set; }
        public string ShellReportFilterName { get; set; }
        public int ShellReportFilterTypeID { get; set; }
        public int ShellReportFilterStatusID { get; set; }
        public int ShellReportID { get; set; }
    
        public virtual ShellReportFilterStatusTable ShellReportFilterStatusTable { get; set; }
        public virtual ShellReportFilterTypeTable ShellReportFilterTypeTable { get; set; }
        public virtual ShellReportTable ShellReportTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ShellReportFilterValueTable> ShellReportFilterValueTables { get; set; }
    }
}
