//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShellComputerGroupEdit0
    {
        public int ShellComputerGroupID { get; set; }
        public string ShellComputerGroupKey { get; set; }
        public string ShellComputerGroupName { get; set; }
    }
}
