//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSales10Edit0
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID { get; set; }
        public Nullable<int> ShellDataPageLinkID { get; set; }
        public Nullable<int> ShellDataPageLineLinkID { get; set; }
        public Nullable<System.DateTime> ShellDateFrom { get; set; }
        public Nullable<System.DateTime> ShellDateTo { get; set; }
        public Nullable<int> StockCustomerGroupID_C { get; set; }
        public Nullable<int> StockCustomerID_C { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public Nullable<int> StockLocationGroupID_C { get; set; }
        public Nullable<int> StockLocationID_CZAll { get; set; }
        public Nullable<int> StockItemGroupID_C { get; set; }
        public Nullable<int> StockItemID_C { get; set; }
        public Nullable<int> cmdNextColumn1 { get; set; }
        public Nullable<int> StockEntryStatusID_CX { get; set; }
        public Nullable<int> ShellComputerID_C { get; set; }
        public Nullable<int> cmdNextRow { get; set; }
        public Nullable<int> StockCompanyParentID_C { get; set; }
        public Nullable<int> StockPayPeriodID_C { get; set; }
        public Nullable<int> TransPayMethodID_C { get; set; }
    }
}
