//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntry2123Edit0
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellMessageID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkStatusID_B { get; set; }
        public Nullable<int> StockEntryID_R { get; set; }
        public System.DateTime ShellDateTo_R { get; set; }
        public System.TimeSpan ShellTimeTo_R { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public int StockLocationID_BR { get; set; }
        public int StockCustomerID_BR { get; set; }
        public double TransQuantity { get; set; }
        public int StockLocationShelfID_O { get; set; }
        public Nullable<int> cmdNextColumn1 { get; set; }
        public double TransAmount_R { get; set; }
        public double TransServiceAmount_R { get; set; }
        public double TransDiscountFactor_R { get; set; }
        public int TransTaxMethodID_BR { get; set; }
        public Nullable<int> cmdNextColumn2 { get; set; }
        public double TransTotalAmount_R { get; set; }
        public double TransDiscountAmount_R { get; set; }
        public double TransTotalTaxAmount_R { get; set; }
        public double TransTotalPayAmount_R { get; set; }
        public Nullable<int> cmdNextColumn3 { get; set; }
        public string StockEntryKey_H { get; set; }
        public string StockEntryName_H { get; set; }
        public int TransPayMethodID_H { get; set; }
        public double TransPayCashAmount_H { get; set; }
        public double TransPayCashChangeAmount_H { get; set; }
        public double TransPayBankAmount_H { get; set; }
        public double TransPayInvoiceAmount_H { get; set; }
        public double TransPayOtherAmount_H { get; set; }
    }
}
