//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMarkupTypeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockMarkupTypeTable()
        {
            this.StockMarkupTables = new HashSet<StockMarkupTable>();
        }
    
        public int StockMarkupTypeID { get; set; }
        public string StockMarkupTypeKey { get; set; }
        public string StockMarkupTypeName { get; set; }
        public string StockMarkupTypeNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockMarkupTable> StockMarkupTables { get; set; }
    }
}
