//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPriceTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockPriceTable()
        {
            this.StockCompanyTables = new HashSet<StockCompanyTable>();
            this.StockPriceLineTables = new HashSet<StockPriceLineTable>();
        }
    
        public int StockPriceID { get; set; }
        public string StockPriceKey { get; set; }
        public string StockPriceName { get; set; }
        public string StockPriceNote { get; set; }
        public int StockPriceTypeID { get; set; }
        public int StockPriceStatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockCompanyTable> StockCompanyTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockPriceLineTable> StockPriceLineTables { get; set; }
        public virtual StockPriceStatusTable StockPriceStatusTable { get; set; }
        public virtual StockPriceTypeTable StockPriceTypeTable { get; set; }
    }
}
