//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPurchase20Edit2
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public Nullable<long> ShellWorkPageLineID_R { get; set; }
        public Nullable<int> ShellMessageID_R { get; set; }
        public Nullable<int> ShellDataPageLinkID { get; set; }
        public Nullable<int> ShellDataPageLineLinkID { get; set; }
        public Nullable<int> StockItemID_C { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> FullPrice { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<double> TaxAmount { get; set; }
        public Nullable<double> FullAmount { get; set; }
        public Nullable<double> Total_Quantity { get; set; }
        public Nullable<double> Total_Amount { get; set; }
        public Nullable<double> Total_TaxAmount { get; set; }
        public Nullable<double> Total_FullAmount { get; set; }
    }
}
