//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemUnitList
    {
        public int StockItemUnitID { get; set; }
        public string StockItemUnitKey { get; set; }
        public string StockItemUnitName { get; set; }
        public int StockItemUnitTypeID { get; set; }
        public int StockItemUnitStatusID { get; set; }
        public int StockItemUnitGroupID { get; set; }
        public int StockItemUnitTypeID_C { get; set; }
        public int StockItemUnitStatusID_C { get; set; }
        public int StockItemUnitGroupID_C { get; set; }
    }
}
