//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSalesItemGroupNameTable
    {
        public int StockCustomerID { get; set; }
        public int StockSalesItemGroupID { get; set; }
        public string StockSalesItemGroupName { get; set; }
        public int StockSalesItemGroupNameID { get; set; }
        public int StockSalesItemGroupNameStatusID { get; set; }
        public int StockItemGroupDiscountID { get; set; }
        public double StockItemGroupDiscountFactor { get; set; }
        public double StockItemGroupDiscountTime { get; set; }
        public double StockItemGroupDiscountDuration { get; set; }
    
        public virtual StockCompanyTable StockCompanyTable { get; set; }
        public virtual StockSalesItemGroupTable StockSalesItemGroupTable { get; set; }
    }
}
