//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemUnitGroupTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockItemUnitGroupTable()
        {
            this.StockItemUnitTables = new HashSet<StockItemUnitTable>();
            this.StockItemUnitGroupTable1 = new HashSet<StockItemUnitGroupTable>();
        }
    
        public int StockItemUnitGroupID { get; set; }
        public string StockItemUnitGroupKey { get; set; }
        public string StockItemUnitGroupName { get; set; }
        public string StockItemUnitGroupNote { get; set; }
        public Nullable<int> StockItemUnitGroupParentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockItemUnitTable> StockItemUnitTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockItemUnitGroupTable> StockItemUnitGroupTable1 { get; set; }
        public virtual StockItemUnitGroupTable StockItemUnitGroupTable2 { get; set; }
    }
}
