//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntry2130Edit2_FiscalDitails
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public Nullable<int> SortID { get; set; }
        public string NonFiscalText { get; set; }
    }
}
