//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntryMatrix_R2
    {
        public int StockEntryID { get; set; }
        public string StockEntryKey { get; set; }
        public string StockEntryName { get; set; }
        public int StockEntryParentID { get; set; }
        public int StockEntryTypeID { get; set; }
        public int StockEntryStatusID { get; set; }
        public System.DateTime StockEntryDate { get; set; }
        public int ShellUserID { get; set; }
        public System.DateTime ShellCreationDate { get; set; }
        public int ShellCreatorUserID { get; set; }
        public System.DateTime ShellModificationDate { get; set; }
        public int ShellModifierUserID { get; set; }
        public int StockPersonID { get; set; }
        public int StockCompanyID { get; set; }
        public double SumFullAmount { get; set; }
        public double SumAmount { get; set; }
        public double SumTaxAmount { get; set; }
        public int StockItemGroupID { get; set; }
        public int StockItemGroupID2 { get; set; }
        public int StockCarID { get; set; }
        public System.DateTime StockEntryDate2 { get; set; }
        public int StockEntrySortID { get; set; }
        public int StockAllocationBaseID { get; set; }
        public int StockEntryID2 { get; set; }
        public int StockPayPeriodID { get; set; }
        public long StockEntryLineID { get; set; }
        public int StockEntryLineSortID { get; set; }
        public int StockEntryLineTypeID { get; set; }
        public int StockEntryLineStatusID { get; set; }
        public long StockEntryLineParentID { get; set; }
        public int StockLocationID { get; set; }
        public int StockItemID { get; set; }
        public int StockItemID2 { get; set; }
        public int StockLocationID2 { get; set; }
        public double StockQuantity { get; set; }
        public double StockAmount { get; set; }
        public double TransQuantity { get; set; }
        public string StockEntryLineName { get; set; }
        public double FullAmount { get; set; }
        public double TaxAmount { get; set; }
        public double Amount { get; set; }
    }
}
