//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSupplierGroupTable
    {
        public int StockSupplierGroupID { get; set; }
        public string StockSupplierGroupKey { get; set; }
        public string StockSupplierGroupName { get; set; }
        public string StockSupplierGroupNote { get; set; }
        public int StockSupplierGroupParentID { get; set; }
        public int StockCompanyTypeID { get; set; }
    }
}
