//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPersonGroupTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockPersonGroupTable()
        {
            this.StockPersonTables = new HashSet<StockPersonTable>();
            this.StockPersonGroupTable1 = new HashSet<StockPersonGroupTable>();
        }
    
        public int StockPersonGroupID { get; set; }
        public string StockPersonGroupKey { get; set; }
        public string StockPersonGroupName { get; set; }
        public string StockPersonGroupNote { get; set; }
        public Nullable<int> StockPersonGroupParentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockPersonTable> StockPersonTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockPersonGroupTable> StockPersonGroupTable1 { get; set; }
        public virtual StockPersonGroupTable StockPersonGroupTable2 { get; set; }
    }
}
