//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntryT13Edit0
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellMessageID { get; set; }
        public System.DateTime StockEntryDateTime { get; set; }
        public Nullable<int> StockEntryID_R { get; set; }
        public int ShellWorkStatusID_B { get; set; }
        public Nullable<int> cmdNextColumn1 { get; set; }
        public int StockLocationID_CZ { get; set; }
        public int StockLocationID_C { get; set; }
        public string StockEntryKey_R { get; set; }
        public Nullable<int> cmdNextColumn2 { get; set; }
        public int StockCustomerID_CR { get; set; }
        public string StockEntryName { get; set; }
        public int RsWaybillTypeID_CR { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public int StockEntryParentID_W { get; set; }
        public double TransAmount_R { get; set; }
        public double TransTaxAmount_R { get; set; }
        public Nullable<int> cmdNextColumn3 { get; set; }
        public int StockPersonID_C { get; set; }
        public int StockCarID_C { get; set; }
        public int StockDeliveryID_C { get; set; }
        public Nullable<int> cmdNextColumn4 { get; set; }
        public int StockCompanyGroupID_CR { get; set; }
    }
}
