//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDiscountMethodTable
    {
        public int StockDiscountMethodID { get; set; }
        public string StockDiscountMethodKey { get; set; }
        public string StockDiscountMethodName { get; set; }
        public string StockDiscountMethodNote { get; set; }
        public int StockDiscountMethodTypeID { get; set; }
        public int StockDiscountMethodStatusID { get; set; }
        public Nullable<System.DateTime> StockDiscountMethodValidFrom { get; set; }
        public Nullable<System.DateTime> StockDiscountMethodValidTo { get; set; }
        public double StockDiscountMethodServiceFactor { get; set; }
        public double StockDiscountMethodfFactor { get; set; }
        public double StockDiscountMethodFiscalFactor { get; set; }
    }
}
