//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBOMPlanEdit9
    {
        public int StockBOMPlanID { get; set; }
        public int StockItemID { get; set; }
        public string StockItemKey { get; set; }
        public string StockItemName { get; set; }
        public Nullable<double> Quantity01 { get; set; }
        public Nullable<double> Quantity02 { get; set; }
        public Nullable<double> Quantity03 { get; set; }
        public Nullable<double> StockRecipeQuantity { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public double StockItemProtein_R { get; set; }
        public double StockItemFat_R { get; set; }
        public double StockItemCarbohydrate_R { get; set; }
        public double StockItemCalorie_R { get; set; }
        public Nullable<int> cmdNextColumn1 { get; set; }
        public Nullable<double> StockItemProtein { get; set; }
        public Nullable<double> StockItemFat { get; set; }
        public Nullable<double> StockItemCarbohydrate { get; set; }
        public Nullable<double> StockItemCalorie { get; set; }
    }
}
