//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemByLocationTable
    {
        public int StockLocationID { get; set; }
        public int StockItemID { get; set; }
        public double StockQuantity { get; set; }
        public double StockAmount { get; set; }
        public double StockCostPrice { get; set; }
        public int SalesItemID { get; set; }
        public int SalesItemUnitID { get; set; }
        public double SalesItemUnitFactor { get; set; }
        public double SalesPrice { get; set; }
        public int SalesTaxID { get; set; }
    }
}
