//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSalesUserGroupTable
    {
        public int StockSalesUserGroupID { get; set; }
        public string StockSalesUserGroupKey { get; set; }
        public string StockSalesUserGroupName { get; set; }
        public bool POSFlag_Sales { get; set; }
        public bool POSFlag_SalesReturn { get; set; }
        public bool POSFlag_Cash { get; set; }
        public bool POSFlag_Sync { get; set; }
        public bool POSFlag_SalesQuantityChange { get; set; }
        public bool POSFlag_SalesCustomerChange { get; set; }
        public bool POSFlag_SalesTaxMethodChange { get; set; }
        public bool POSFlag_CashIn { get; set; }
        public bool POSFlag_CashOut { get; set; }
        public bool POSFlag_CashX { get; set; }
        public bool POSFlag_CashZ { get; set; }
    }
}
