//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMarkupTable
    {
        public int StockMarkupID { get; set; }
        public string StockMarkupKey { get; set; }
        public string StockMarkupName { get; set; }
        public int StockMarkupTypeID { get; set; }
        public int StockMarkupStatusID { get; set; }
        public int StockMarkupGroupID { get; set; }
        public int StockCustomerID { get; set; }
        public int StockSupplierID { get; set; }
        public double StockMarkupFactor { get; set; }
        public double StockMarkupValue { get; set; }
        public double StockMarkupRoundFactor { get; set; }
    
        public virtual StockMarkupGroupTable StockMarkupGroupTable { get; set; }
        public virtual StockMarkupStatusTable StockMarkupStatusTable { get; set; }
        public virtual StockMarkupTypeTable StockMarkupTypeTable { get; set; }
    }
}
