//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockCustomerGroupTable
    {
        public int StockCustomerGroupID { get; set; }
        public string StockCustomerGroupKey { get; set; }
        public string StockCustomerGroupName { get; set; }
        public string StockCustomerGroupNote { get; set; }
        public int StockCustomerGroupParentID { get; set; }
        public int StockCompanyTypeID { get; set; }
    }
}
