//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSalesItemStatusTable
    {
        public int StockSalesItemStatusID { get; set; }
        public string StockSalesItemStatusKey { get; set; }
        public string StockSalesItemStatusName { get; set; }
    }
}
