//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemT1GroupEdit0
    {
        public int StockItemT1GroupID { get; set; }
        public string StockItemT1GroupKey { get; set; }
        public string StockItemT1GroupName { get; set; }
        public int StockItemT1GroupParentID_H { get; set; }
        public int StockItemTypeID { get; set; }
        public Nullable<int> cmdNextColumn1 { get; set; }
        public int StockItemGroupDiscountID_C { get; set; }
        public double StockItemGroupDiscountFactor { get; set; }
        public double StockItemGroupDiscountTime { get; set; }
        public double StockItemGroupDiscountDuration { get; set; }
    }
}
