//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPlanningMethodTable
    {
        public int StockPlanningMethodID { get; set; }
        public string StockPlanningMethodKey { get; set; }
        public string StockPlanningMethodName { get; set; }
        public int StockPlanningMethodSortID { get; set; }
        public int StockPlanningMethodStatusID { get; set; }
        public int StockPlanningMethodTypeID { get; set; }
    }
}
