//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemT2TypeTable
    {
        public int StockItemT2TypeID { get; set; }
        public string StockItemT2TypeKey { get; set; }
        public string StockItemT2TypeName { get; set; }
        public string StockItemT2TypeNote { get; set; }
    }
}
