//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemT2GroupEdit5
    {
        public int StockItemT2ID { get; set; }
        public string StockItemKey { get; set; }
        public string StockItemName { get; set; }
        public int StockItemTypeID { get; set; }
        public int StockItemT2GroupID { get; set; }
        public int StockItemUnitID_C { get; set; }
        public int StockTaxID_A { get; set; }
        public int StockItemValidDays { get; set; }
        public int StockItemSortID { get; set; }
        public double StockItemNWeight { get; set; }
        public double StockItemGWeight { get; set; }
        public double StockQuantity3 { get; set; }
    }
}
