//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPersonEdit0
    {
        public int StockPersonID { get; set; }
        public string StockPersonKey { get; set; }
        public string StockPersonName { get; set; }
        public int StockPersonTypeID_C { get; set; }
        public int StockPersonStatusID_C { get; set; }
        public int StockPersonGroupID_C { get; set; }
        public Nullable<int> cmdNextRow2 { get; set; }
        public string StockPersonBirthAddress { get; set; }
        public Nullable<System.DateTime> StockPersonBirthDate { get; set; }
        public string StockPersonGender { get; set; }
        public string StockPersonMaritalStatus { get; set; }
        public string StockPersonPersonalNumber { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public string StockPersonAddress { get; set; }
        public string StockPersonAddress2 { get; set; }
        public string StockPersonMobile { get; set; }
        public string StockPersonPhone { get; set; }
        public string StockPersonMail { get; set; }
        public string StockPersonDriverLicense { get; set; }
    }
}
