//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemT2Table
    {
        public int StockItemT2ID { get; set; }
        public string StockItemT2Key { get; set; }
        public string StockItemT2Name { get; set; }
        public int StockItemTypeID { get; set; }
        public int StockItemT2StatusID { get; set; }
        public int StockItemT2GroupID { get; set; }
        public int StockItemUnitID { get; set; }
        public int StockItemValidDays { get; set; }
        public double StockItemProtein { get; set; }
        public double StockItemFat { get; set; }
        public double StockItemCarbohydrate { get; set; }
        public double StockItemCalorie { get; set; }
        public string StockItemBarcodeKey { get; set; }
        public double StockItemValidHours { get; set; }
    }
}
