//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemT1Table
    {
        public int StockItemT1ID { get; set; }
        public string StockItemT1Key { get; set; }
        public string StockItemT1Name { get; set; }
        public string StockItemT1Note { get; set; }
        public int StockItemT1GroupID { get; set; }
        public int StockItemT1SortID { get; set; }
        public int StockItemT1StatusID { get; set; }
        public int StockItemT1TypeID { get; set; }
        public int StockItemUnitID { get; set; }
        public double StockItemProtein { get; set; }
        public double StockItemFat { get; set; }
        public double StockItemCarbohydrate { get; set; }
        public double StockItemCalorie { get; set; }
        public string StockItemBarcodeKey { get; set; }
        public double StockItemValidHours { get; set; }
        public string StockItemNote2 { get; set; }
    }
}
