//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockCustomerStatusTable
    {
        public int StockCustomerStatusID { get; set; }
        public string StockCustomerStatusKey { get; set; }
        public string StockCustomerStatusName { get; set; }
        public string StockCustomerStatusNote { get; set; }
    }
}
