//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemT2Edit0
    {
        public int StockItemT2ID { get; set; }
        public string StockItemT2Key { get; set; }
        public string StockItemT2Name { get; set; }
        public int StockItemUnitID_C { get; set; }
        public Nullable<int> cmdNextRow { get; set; }
        public int StockItemSortID { get; set; }
        public int StockItemTypeID_CR { get; set; }
        public int StockItemStatusID_C { get; set; }
        public int StockItemT2GroupID_C { get; set; }
        public int StockTaxID_C { get; set; }
        public double StockItemNWeight { get; set; }
        public double StockItemGWeight { get; set; }
        public Nullable<int> cmdNextRow1 { get; set; }
        public double StockQuantity3 { get; set; }
        public string StockItemNote { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public double StockItemProtein_R { get; set; }
        public double StockItemFat_R { get; set; }
        public double StockItemCarbohydrate_R { get; set; }
        public double StockItemCalorie_R { get; set; }
        public string StockItemBarcodeKey { get; set; }
        public double StockItemValidHours { get; set; }
        public string StockItemNote2 { get; set; }
    }
}
