//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockCompanyGroupTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockCompanyGroupTable()
        {
            this.StockCompanyTables = new HashSet<StockCompanyTable>();
            this.StockCompanyGroupTable1 = new HashSet<StockCompanyGroupTable>();
        }
    
        public int StockCompanyGroupID { get; set; }
        public string StockCompanyGroupKey { get; set; }
        public string StockCompanyGroupName { get; set; }
        public string StockCompanyGroupNote { get; set; }
        public int StockCompanyGroupParentID { get; set; }
        public int StockCompanyTypeID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockCompanyTable> StockCompanyTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockCompanyGroupTable> StockCompanyGroupTable1 { get; set; }
        public virtual StockCompanyGroupTable StockCompanyGroupTable2 { get; set; }
    }
}
