//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSales10Edit1
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public int ShellMessageID_R { get; set; }
        public int ShellDataPageLinkID { get; set; }
        public int ShellDataPageLineLinkID { get; set; }
        public Nullable<System.DateTime> StockEntryDateTime { get; set; }
        public Nullable<int> StockCustomerID_CR { get; set; }
        public double Amount { get; set; }
        public double TaxAmount { get; set; }
        public double FullAmount { get; set; }
        public double StockAmount { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public Nullable<double> StockCompanyCardID_A { get; set; }
        public double StockAmountLimitR { get; set; }
        public Nullable<int> StockEntryID_R { get; set; }
        public string StockEntryKey_R { get; set; }
        public string StockEntryName_R { get; set; }
        public Nullable<int> StockLocationID_CR { get; set; }
        public Nullable<int> TransPayMethodID_CR { get; set; }
        public Nullable<int> StockEntryID2 { get; set; }
        public Nullable<int> ShellComputerID_C { get; set; }
        public Nullable<double> Total_Amount { get; set; }
        public Nullable<double> Total_TaxAmount { get; set; }
        public Nullable<double> Total_FullAmount { get; set; }
        public Nullable<double> Total_StockAmount { get; set; }
    }
}
