//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSupplierEdit0
    {
        public int StockSupplierID { get; set; }
        public string StockSupplierKey { get; set; }
        public string StockSupplierName { get; set; }
        public string StockSupplierNote { get; set; }
        public Nullable<int> cmdNextRow { get; set; }
        public int StockSupplierGroupID_C { get; set; }
        public int StockSupplierSortID { get; set; }
        public int StockSupplierStatusID_C { get; set; }
        public int StockCompanyTypeID_CR { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public string StockSupplierTaxNumber { get; set; }
        public int StockTaxID_C { get; set; }
        public Nullable<int> cmdNextRow1 { get; set; }
        public string StockSupplierAddress { get; set; }
        public string StockSupplierAddress2 { get; set; }
        public string StockSupplierAddress3 { get; set; }
        public string StockSupplierPhone { get; set; }
        public string StockSupplierFax { get; set; }
        public string StockSupplierMail { get; set; }
        public string StockSupplierWeb { get; set; }
    }
}
