//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemT0Edit0
    {
        public int StockItemT0ID { get; set; }
        public string StockItemT0Key { get; set; }
        public string StockItemT0Name { get; set; }
        public string StockItemT0Note { get; set; }
        public Nullable<int> cmdNextRow { get; set; }
        public int StockItemT0GroupID_C { get; set; }
        public int StockItemT0SortID { get; set; }
        public int StockItemT0StatusID_C { get; set; }
        public int StockItemTypeID_CR { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public int StockItemUnitID_C { get; set; }
        public int StockTaxID_C { get; set; }
        public Nullable<int> cmdNextRow1 { get; set; }
        public int StockItemT1ID_C { get; set; }
        public double StockQuantity2 { get; set; }
        public Nullable<int> cmdNextColumn1 { get; set; }
        public double StockItemProtein { get; set; }
        public double StockItemFat { get; set; }
        public double StockItemCarbohydrate { get; set; }
        public double StockItemCalorie { get; set; }
        public string StockItemBarcodeKey { get; set; }
    }
}
