//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLocationEdit6
    {
        public int StockLocationID { get; set; }
        public int StockLocationShelfSortID { get; set; }
        public string StockLocationShelfKey { get; set; }
        public string StockLocationShelfName { get; set; }
        public int StockLocationShelfTypeID_C { get; set; }
        public int StockLocationShelfStatusID_C { get; set; }
    }
}
