//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSalesPriceList
    {
        public long StockSalesPriceID { get; set; }
        public string StockSalesPriceKey { get; set; }
        public string StockSalesPriceName { get; set; }
        public int StockSalePriceTypeID { get; set; }
        public double FCPrice { get; set; }
        public int StockTaxID_C { get; set; }
        public System.DateTime StockPriceLineValidFrom { get; set; }
        public double StockBasePrice { get; set; }
        public double StockBasePriceFactor { get; set; }
        public System.DateTime ShellCreationDate { get; set; }
        public int StockSalesPriceStatusID { get; set; }
        public int StockSalesPriceGroupID { get; set; }
        public int StockSalesPriceGroupID_C { get; set; }
        public int StockEntryID { get; set; }
        public Nullable<int> StockSalesPriceUpdate { get; set; }
    }
}
