//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockCarList
    {
        public int StockCarID { get; set; }
        public string StockCarKey { get; set; }
        public string StockCarName { get; set; }
        public int StockCarTypeID { get; set; }
        public int StockCarStatusID { get; set; }
        public int StockCarGroupID { get; set; }
        public int StockCarTypeID_C { get; set; }
        public int StockCarStatusID_C { get; set; }
        public int StockCarGroupID_C { get; set; }
    }
}
