//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemT3Edit4
    {
        public int StockRecipeID { get; set; }
        public int StockRecipeSortID { get; set; }
        public int StockItemT3ID { get; set; }
        public int StockItemT2ID_C { get; set; }
        public double StockRecipeQuantity { get; set; }
        public int StockRecipeStatusID_C { get; set; }
        public System.DateTime StockRecipeValidFrom { get; set; }
        public Nullable<System.DateTime> StockRecipeValidTo { get; set; }
        public string StockRecipeKey { get; set; }
        public string StockRecipeName { get; set; }
    }
}
