//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBudget00Edit2
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public int ShellMessageID_R { get; set; }
        public int ShellDataPageLinkID { get; set; }
        public int ShellDataPageLineLinkID { get; set; }
        public Nullable<int> StockItemID_CR { get; set; }
        public Nullable<int> StockBudgetTypeID_B { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public double Quantity01 { get; set; }
        public double Quantity02 { get; set; }
        public double Quantity03 { get; set; }
        public double Quantity04 { get; set; }
        public double Quantity05 { get; set; }
        public double Quantity06 { get; set; }
        public double Quantity07 { get; set; }
        public double Quantity08 { get; set; }
        public double Quantity09 { get; set; }
        public double Quantity10 { get; set; }
        public double Quantity11 { get; set; }
        public double Quantity12 { get; set; }
        public double Quantity13 { get; set; }
        public double Quantity14 { get; set; }
        public double Quantity15 { get; set; }
    }
}
