//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntry2120Edit1
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellMessageID_R { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public int StockSalesItemID_AR { get; set; }
        public string StockItemName_R { get; set; }
        public Nullable<int> StockWork2120_QuantityDecrease { get; set; }
        public double TransQuantityInitial { get; set; }
        public Nullable<int> StockWork2120_QuantityIncrease { get; set; }
        public double TransQuantity_R { get; set; }
        public Nullable<int> StockWork2120_QuantityReorder { get; set; }
        public int TransQuantityFlagPrepare_R { get; set; }
        public double TransPrice_R { get; set; }
        public double TransAmount_R { get; set; }
        public string StockEntryName { get; set; }
    }
}
