//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntryTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockEntryTable()
        {
            this.StockEntryLineTables = new HashSet<StockEntryLineTable>();
            this.StockPriceLineTables = new HashSet<StockPriceLineTable>();
        }
    
        public int StockEntryID { get; set; }
        public int StockEntryID2 { get; set; }
        public string StockEntryKey { get; set; }
        public string StockEntryName { get; set; }
        public int StockEntryParentID { get; set; }
        public int StockEntryParentID2 { get; set; }
        public int StockEntryTypeID { get; set; }
        public int StockEntryStatusID { get; set; }
        public int StockEntrySortID { get; set; }
        public System.DateTime StockEntryDate { get; set; }
        public System.DateTime StockEntryDate2 { get; set; }
        public int StockItemGroupID { get; set; }
        public int StockItemGroupID2 { get; set; }
        public int StockLocationID { get; set; }
        public int StockLocationID2 { get; set; }
        public int StockPersonID { get; set; }
        public int StockCarID { get; set; }
        public int StockDeliveryID { get; set; }
        public int StockAllocationBaseID { get; set; }
        public int StockPayPeriodID { get; set; }
        public string TextCompanyKey { get; set; }
        public string TextCompanyName { get; set; }
        public string TextCompanyAddress { get; set; }
        public string TextStockPersonKey { get; set; }
        public string TextStockPersonName { get; set; }
        public string TextStockCarKey { get; set; }
        public string TextStockCarName { get; set; }
        public long RSWaybillID { get; set; }
        public string RSWaybillKey { get; set; }
        public long RSWaybillParentID { get; set; }
        public string RSWaybillParentKey { get; set; }
        public int RSWaybillConfirmID { get; set; }
        public int RSMessageID { get; set; }
        public int RSMessageCounterID { get; set; }
        public int RSSyncProcessID { get; set; }
        public System.DateTime RSSyncDate { get; set; }
        public int ShellUserID { get; set; }
        public int ShellComputerID { get; set; }
        public int ShellCustomerID { get; set; }
        public System.DateTime ShellCreationDate { get; set; }
        public int ShellCreatorUserID { get; set; }
        public System.DateTime ShellModificationDate { get; set; }
        public int ShellModifierUserID { get; set; }
        public int ShellSyncProcessID { get; set; }
        public System.DateTime ShellSyncDate { get; set; }
        public int TransCompanyID { get; set; }
        public int TransCompanyID2 { get; set; }
        public int TransCompanyCardID { get; set; }
        public int TransTaxMethodID { get; set; }
        public double TransTaxMethodFactor { get; set; }
        public int TransPayMethodID { get; set; }
        public double TransAmount { get; set; }
        public double TransTaxAmount { get; set; }
        public double TransBaseAmount { get; set; }
        public int TransServiceID { get; set; }
        public double TransServiceFactor { get; set; }
        public double TransServiceAmount { get; set; }
        public double TransServiceTaxAmount { get; set; }
        public double TransServiceBaseAmount { get; set; }
        public int TransDiscountID { get; set; }
        public double TransDiscountFactor { get; set; }
        public double TransDiscountAmount { get; set; }
        public double TransDiscountTaxAmount { get; set; }
        public double TransDiscountBaseAmount { get; set; }
        public double TransTotalAmount { get; set; }
        public double TransTotalTaxAmount { get; set; }
        public double TransTotalBaseAmount { get; set; }
        public double TransTotalPayAmount { get; set; }
        public double TransPayCashAmount { get; set; }
        public double TransPayCashChangeAmount { get; set; }
        public double TransPayBankAmount { get; set; }
        public double TransPayInvoiceAmount { get; set; }
        public double TransPayOtherAmount { get; set; }
        public double TransQuantity { get; set; }
        public double TransLocationShelfID { get; set; }
        public int RSWaybillTypeID { get; set; }
    
        public virtual ShellUserTable ShellUserTable { get; set; }
        public virtual StockCarTable StockCarTable { get; set; }
        public virtual StockCompanyTable StockCompanyTable { get; set; }
        public virtual StockCompanyTable StockCompanyTable1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockEntryLineTable> StockEntryLineTables { get; set; }
        public virtual StockEntryStatusTable StockEntryStatusTable { get; set; }
        public virtual StockEntryTypeTable StockEntryTypeTable { get; set; }
        public virtual StockPersonTable StockPersonTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockPriceLineTable> StockPriceLineTables { get; set; }
    }
}
