//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDeliveryStatusTable
    {
        public int StockDeliveryStatusID { get; set; }
        public string StockDeliveryStatusKey { get; set; }
        public string StockDeliveryStatusName { get; set; }
        public string StockDeliveryStatusNote { get; set; }
    }
}
