//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDeliveryGroupEdit0
    {
        public int StockDeliveryGroupID { get; set; }
        public string StockDeliveryGroupKey { get; set; }
        public string StockDeliveryGroupName { get; set; }
    }
}
