//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockCustomerEdit0
    {
        public int StockCustomerID { get; set; }
        public string StockCustomerKey { get; set; }
        public string StockCustomerName { get; set; }
        public string StockCustomerNote { get; set; }
        public Nullable<int> cmdNextRow { get; set; }
        public int StockCustomerGroupID_C { get; set; }
        public int StockCustomerSortID { get; set; }
        public int StockCustomerStatusID_C { get; set; }
        public int StockCompanyTypeID_CR { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public string StockCustomerTaxNumber { get; set; }
        public int StockTaxID_C { get; set; }
        public int TransTaxMethodID_C { get; set; }
        public int StockSalesPriceGroupID_C { get; set; }
        public double TransPriceDiscountFactor { get; set; }
        public Nullable<int> cmdNextRow1 { get; set; }
        public string StockCustomerAddress { get; set; }
        public string StockCustomerAddress2 { get; set; }
        public string StockCustomerAddress3 { get; set; }
        public string StockCustomerPhone { get; set; }
        public string StockCustomerFax { get; set; }
        public string StockCustomerMail { get; set; }
        public string StockCustomerWeb { get; set; }
        public int StockPlanningMethodID_C { get; set; }
    }
}
