//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPBalance10Edit1
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public int ShellMessageID_R { get; set; }
        public int ShellDataPageLinkID { get; set; }
        public int ShellDataPageLineLinkID { get; set; }
        public Nullable<int> StockCustomerID_CR { get; set; }
        public Nullable<int> StockItemID_CR { get; set; }
        public double StockQuantity_B { get; set; }
        public double StockQuantity_I { get; set; }
        public double StockQuantity_O { get; set; }
        public double StockQuantity_E { get; set; }
        public Nullable<double> Total_StockQuantity_B { get; set; }
        public Nullable<double> Total_StockQuantity_I { get; set; }
        public Nullable<double> Total_StockQuantity_O { get; set; }
        public Nullable<double> Total_StockQuantity_E { get; set; }
    }
}
