//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLocationEdit4
    {
        public int StockLocationID { get; set; }
        public int StockLocationItemSortID { get; set; }
        public int StockItemID_C { get; set; }
        public double MinQuantity { get; set; }
        public double OrderFactor { get; set; }
        public double MaxQuantity { get; set; }
        public double MinDays { get; set; }
        public double MaxDays { get; set; }
        public double DMQuantity { get; set; }
        public int StockRPTypeID_A { get; set; }
        public int StockDeliveryGraphID_A { get; set; }
        public double OrderDays { get; set; }
        public int StockDeliveryTypeID_A { get; set; }
        public int StockUsageTypeID_A { get; set; }
        public Nullable<int> StockLocationID_CSF { get; set; }
        public int StockLocationItemStatusID_C { get; set; }
        public Nullable<int> StockSupplierID_C { get; set; }
    }
}
