//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemT3Edit0
    {
        public int StockItemT3ID { get; set; }
        public string StockItemT3Key { get; set; }
        public string StockItemT3Name { get; set; }
        public int StockItemUnitID_C { get; set; }
        public int StockItemValidDays { get; set; }
        public Nullable<int> cmdNextRow { get; set; }
        public int StockItemSortID { get; set; }
        public int StockItemTypeID_CR { get; set; }
        public int StockItemStatusID_C { get; set; }
        public int StockItemGroupID_C { get; set; }
        public int StockTaxID_C { get; set; }
        public int StockMarkupGroupID_C { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public double StockItemProtein_R { get; set; }
        public double StockItemFat_R { get; set; }
        public double StockItemCarbohydrate_R { get; set; }
        public double StockItemCalorie_R { get; set; }
    }
}
