//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockWorkLiveTable
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID { get; set; }
        public int ShellMessageID { get; set; }
        public Nullable<System.DateTime> ShellDateFrom { get; set; }
        public Nullable<System.DateTime> ShellDateTo { get; set; }
        public Nullable<int> StockLocationID { get; set; }
        public Nullable<int> StockItemID { get; set; }
        public double StockQuantity { get; set; }
        public double StockQuantity1 { get; set; }
        public double StockQuantity2 { get; set; }
        public double StockQuantity3 { get; set; }
        public double StockQuantity4 { get; set; }
        public double StockQuantity5 { get; set; }
        public double StockQuantity6 { get; set; }
        public double StockQuantity7 { get; set; }
        public double StockQuantity8 { get; set; }
        public double StockQuantity9 { get; set; }
        public double StockAmount { get; set; }
        public double StockAmount1 { get; set; }
        public double StockAmount2 { get; set; }
        public double StockAmount3 { get; set; }
        public double StockAmount4 { get; set; }
        public double StockAmount5 { get; set; }
        public double StockAmount6 { get; set; }
        public double StockAmount7 { get; set; }
        public double StockAmount8 { get; set; }
        public double StockAmount9 { get; set; }
        public Nullable<System.DateTime> StockEntryDate { get; set; }
        public Nullable<int> StockEntryID { get; set; }
        public Nullable<int> StockEntryLineSortID { get; set; }
        public Nullable<int> StockEntryTypeID { get; set; }
        public string StockEntryKey { get; set; }
        public string StockEntryName { get; set; }
        public Nullable<long> StockEntryLineID { get; set; }
        public Nullable<int> StockEntryLineTypeID { get; set; }
        public int ShellYesNo { get; set; }
        public int ShellYesNo1 { get; set; }
        public int ShellYesNo2 { get; set; }
        public int ShellYesNo3 { get; set; }
        public int ShellYesNo4 { get; set; }
        public int ShellYesNo5 { get; set; }
        public Nullable<int> ShellWorkPageParentID { get; set; }
        public Nullable<int> ShellWorkPageLineParentID { get; set; }
        public Nullable<int> StockCompanyID { get; set; }
        public Nullable<int> StockCompanyGroupID { get; set; }
        public Nullable<int> StockItemGroupID { get; set; }
        public Nullable<int> StockLocationGroupID { get; set; }
        public double Amount { get; set; }
        public double TaxAmount { get; set; }
        public double FullAmount { get; set; }
        public double Price { get; set; }
        public Nullable<System.DateTime> StockEntryDate2 { get; set; }
        public Nullable<int> TaxCodeID { get; set; }
        public double Price1 { get; set; }
        public double Price2 { get; set; }
        public double Price3 { get; set; }
        public double Price4 { get; set; }
        public double Price5 { get; set; }
        public Nullable<int> StockSalesPriceGroupID { get; set; }
        public int StockEntryCount { get; set; }
        public Nullable<int> StockEntryParentID { get; set; }
        public Nullable<long> StockEntryLineParentID { get; set; }
        public double StockPrice { get; set; }
        public double StockPrice1 { get; set; }
        public double FullPrice { get; set; }
        public Nullable<int> StockUserID { get; set; }
        public Nullable<int> StockPersonID { get; set; }
        public Nullable<int> StockCarID { get; set; }
        public Nullable<int> StockLocationID2 { get; set; }
        public double StockItemNWeight { get; set; }
        public double StockItemGWeight { get; set; }
        public Nullable<int> StockEntryStatusID { get; set; }
        public Nullable<int> StockEntryID2 { get; set; }
        public Nullable<int> StockPriceID { get; set; }
        public Nullable<int> TaxCodeID1 { get; set; }
        public Nullable<int> StockItemID2 { get; set; }
        public Nullable<int> StockItemID3 { get; set; }
        public Nullable<int> StockBOMPlanLineTypeID { get; set; }
        public double Percent1 { get; set; }
        public double Percent2 { get; set; }
        public double Percent3 { get; set; }
        public double Percent4 { get; set; }
        public double Percent5 { get; set; }
        public double Percent { get; set; }
        public Nullable<int> ShellComputerID { get; set; }
        public Nullable<int> StockCompanyParentID { get; set; }
        public Nullable<int> StockEntryProcessID { get; set; }
        public Nullable<int> StockPayPeriodID { get; set; }
        public Nullable<int> StockShelfID { get; set; }
        public Nullable<int> TransPayMethodID { get; set; }
        public Nullable<System.TimeSpan> ShellTimeFrom { get; set; }
        public Nullable<System.TimeSpan> ShellTimeTo { get; set; }
        public Nullable<int> StockCostCodeID { get; set; }
        public Nullable<int> StockSalesUserID { get; set; }
        public Nullable<int> ShellCreatorUserID { get; set; }
        public Nullable<System.DateTime> StockCalculationDate { get; set; }
        public Nullable<int> StockRecipeItemID { get; set; }
        public Nullable<double> StockRecipeQuantity { get; set; }
        public Nullable<double> FCPrice { get; set; }
        public Nullable<double> StockPurchaseQuantity { get; set; }
        public Nullable<double> StockPurchaseAmount { get; set; }
        public Nullable<double> StockWoffQuantity { get; set; }
        public Nullable<double> StockWoffAmount { get; set; }
        public Nullable<double> TransPrice { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> TransQuantity { get; set; }
        public string Comment { get; set; }
        public Nullable<double> StockCompanyCardID { get; set; }
        public Nullable<int> TransItemID { get; set; }
    }
}
