//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSupplierStatusTable
    {
        public int StockSupplierStatusID { get; set; }
        public string StockSupplierStatusKey { get; set; }
        public string StockSupplierStatusName { get; set; }
        public string StockSupplierStatusNote { get; set; }
    }
}
