//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemT0Edit4
    {
        public int StockItemT0ID { get; set; }
        public string StockItemBarcodeKey { get; set; }
        public string StockItemBarcodeName { get; set; }
    }
}
