//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntryI10Edit0
    {
        public int ShellMessageID_R { get; set; }
        public int ShellWorkStatusID_B { get; set; }
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public Nullable<int> StockEntryID_R { get; set; }
        public System.DateTime ShellDateTime_To { get; set; }
        public string StockEntryKey { get; set; }
        public string StockEntryName_Ixx { get; set; }
        public int StockItemGroupID_AFrom { get; set; }
        public int StockItemGroupID_ATo { get; set; }
        public Nullable<int> cmdNextRow { get; set; }
        public int StockLocationID_CZ { get; set; }
        public int StockCustomerID_CR { get; set; }
        public int StockPersonID_C { get; set; }
        public double FCFullAmount_R { get; set; }
        public double FCTaxAmount_R { get; set; }
        public double FCAmount_R { get; set; }
    }
}
