//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntry2120Edit2
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellMessageID_R { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public int TransPayMethodID_CR { get; set; }
        public double TransPayAmount_R { get; set; }
        public double TransPayChangeAmount_R { get; set; }
        public string StockEntryKey_R { get; set; }
        public int StockPayPeriodID_R { get; set; }
        public System.DateTime ShellDateTime_R { get; set; }
    }
}
