//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockValuationTable
    {
        public int ShellUserID { get; set; }
        public int StockItemID { get; set; }
        public int StockLocationID { get; set; }
        public double StockQuantity000 { get; set; }
        public double StockAmount000 { get; set; }
        public double StockQuantity001 { get; set; }
        public double StockAmount001 { get; set; }
        public double StockQuantity101 { get; set; }
        public double StockAmount101 { get; set; }
        public double StockQuantity102 { get; set; }
        public double StockAmount102 { get; set; }
        public double StockQuantity103 { get; set; }
        public double StockAmount103 { get; set; }
        public double StockQuantity201 { get; set; }
        public double StockAmount201 { get; set; }
        public double StockQuantity202 { get; set; }
        public double StockAmount202 { get; set; }
        public double StockQuantity301 { get; set; }
        public double StockAmount301 { get; set; }
        public double StockQuantity401 { get; set; }
        public double StockAmount401 { get; set; }
        public double StockQuantity402 { get; set; }
        public double StockAmount402 { get; set; }
        public double StockQuantity501 { get; set; }
        public double StockAmount501 { get; set; }
        public double StockQuantity502 { get; set; }
        public double StockAmount502 { get; set; }
        public double StockQuantity601 { get; set; }
        public double StockAmount601 { get; set; }
        public double StockQuantity602 { get; set; }
        public double StockAmount602 { get; set; }
        public double StockQuantity701 { get; set; }
        public double StockAmount701 { get; set; }
        public double StockQuantity702 { get; set; }
        public double StockAmount702 { get; set; }
        public double StockQuantity { get; set; }
        public double StockAmount { get; set; }
        public double StockCostQuantity { get; set; }
        public double StockCostAmount { get; set; }
        public double StockCostPrice { get; set; }
        public double StockCostPriceLast { get; set; }
    }
}
