//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBudget00Edit3
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public int ShellMessageID_R { get; set; }
        public int ShellDataPageLinkID { get; set; }
        public int ShellDataPageLineLinkID { get; set; }
        public Nullable<int> StockItemID_CR { get; set; }
        public Nullable<int> StockBudgetTypeID_B { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public double Quantity16 { get; set; }
        public double Quantity17 { get; set; }
        public double Quantity18 { get; set; }
        public double Quantity19 { get; set; }
        public double Quantity20 { get; set; }
        public double Quantity21 { get; set; }
        public double Quantity22 { get; set; }
        public double Quantity23 { get; set; }
        public double Quantity24 { get; set; }
        public double Quantity25 { get; set; }
        public double Quantity26 { get; set; }
        public double Quantity27 { get; set; }
        public double Quantity28 { get; set; }
        public double Quantity29 { get; set; }
        public double Quantity30 { get; set; }
        public double Quantity31 { get; set; }
    }
}
