//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemT0GroupEdit1
    {
        public int StockItemT0ID { get; set; }
        public string StockItemT0Key { get; set; }
        public string StockItemT0Name { get; set; }
        public int StockItemT0SortID { get; set; }
        public int StockItemT0StatusID { get; set; }
        public int StockItemT0GroupID { get; set; }
        public int StockItemUnitID_C { get; set; }
        public int StockTaxID_C { get; set; }
        public int StockItemT1ID_C { get; set; }
        public double StockQuantity2 { get; set; }
        public int StockItemT0TypeID { get; set; }
    }
}
