//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSalesPriceGroupEdit5
    {
        public long StockSalesPriceID { get; set; }
        public int StockSalesPriceGroupID { get; set; }
        public int StockSalesPriceSortID { get; set; }
        public int StockItemID_C { get; set; }
        public double FCPrice { get; set; }
        public int StockTaxID_C { get; set; }
        public int StockPriceLineTypeID_C { get; set; }
        public System.DateTime StockPriceLineValidFrom { get; set; }
        public int StockSalesPriceStatusID_C { get; set; }
        public System.DateTime ShellCreationDate { get; set; }
        public int StockSalesItemGroupID_A { get; set; }
    }
}
