//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLiveHeaders00Edit1
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public int ShellDataPageLinkID { get; set; }
        public int ShellDataPageLineLinkID { get; set; }
        public Nullable<System.DateTime> StockEntryDate_R { get; set; }
        public Nullable<int> StockCompanyID_CR { get; set; }
        public double Amount_R { get; set; }
        public double TaxAmount_R { get; set; }
        public double FullAmount_R { get; set; }
        public double StockAmount { get; set; }
        public double StockItemNWeight { get; set; }
        public double StockItemGWeight { get; set; }
        public Nullable<int> StockLocationID_AR { get; set; }
        public Nullable<int> StockEntryTypeID_CR { get; set; }
        public Nullable<int> StockEntryID_R { get; set; }
        public string StockEntryKey_R { get; set; }
        public string StockEntryName_R { get; set; }
        public Nullable<int> ShellUserID_CR { get; set; }
        public Nullable<double> Total_StockQuantity { get; set; }
        public Nullable<double> Total_Amount { get; set; }
        public Nullable<double> Total_TaxAmount { get; set; }
        public Nullable<double> Total_FullAmount { get; set; }
        public Nullable<double> Total_StockAmount { get; set; }
        public Nullable<double> Total_StockItemNWeight { get; set; }
        public Nullable<double> Total_StockItemGWeight { get; set; }
    }
}
