//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockMarkupGroupTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockMarkupGroupTable()
        {
            this.StockItemTables = new HashSet<StockItemTable>();
            this.StockMarkupTables = new HashSet<StockMarkupTable>();
            this.StockMarkupGroupTable1 = new HashSet<StockMarkupGroupTable>();
        }
    
        public int StockMarkupGroupID { get; set; }
        public string StockMarkupGroupKey { get; set; }
        public string StockMarkupGroupName { get; set; }
        public string StockMarkupGroupNote { get; set; }
        public Nullable<int> StockMarkupGroupParentID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockItemTable> StockItemTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockMarkupTable> StockMarkupTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockMarkupGroupTable> StockMarkupGroupTable1 { get; set; }
        public virtual StockMarkupGroupTable StockMarkupGroupTable2 { get; set; }
    }
}
