//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPersonList
    {
        public int StockPersonID { get; set; }
        public string StockPersonKey { get; set; }
        public string StockPersonName { get; set; }
        public int StockPersonTypeID { get; set; }
        public int StockPersonStatusID { get; set; }
        public int StockPersonGroupID { get; set; }
        public string StockPersonAddress { get; set; }
        public string StockPersonMobile { get; set; }
    }
}
