//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntrySP9Edit12
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellMessageID_R { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public Nullable<int> ShellWorkPageParentID { get; set; }
        public string ShellWorkPageLineParentID { get; set; }
        public int StockItemID_C { get; set; }
        public double StockItemBOMFactor_R { get; set; }
        public double TransQuantityFactor { get; set; }
        public int StockLocationID_CR { get; set; }
    }
}
