//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockWorkTable
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID { get; set; }
        public Nullable<int> ShellWorkPageParentID { get; set; }
        public string ShellWorkPageLineParentID { get; set; }
        public double ShellWorkPageSign { get; set; }
        public int ShellWorkPageAuto { get; set; }
        public int ShellMessageID { get; set; }
        public int ShellWorkStatusID { get; set; }
        public int ShellComputerID { get; set; }
        public int ShellCreatorUserID { get; set; }
        public System.DateTime ShellCreationDate { get; set; }
        public int ShellModifierUserID { get; set; }
        public System.DateTime ShellModificationDate { get; set; }
        public Nullable<int> StockEntryID { get; set; }
        public int StockEntryID2 { get; set; }
        public long StockEntryLineID { get; set; }
        public string StockEntryKey { get; set; }
        public string StockEntryName { get; set; }
        public System.DateTime StockEntryDate { get; set; }
        public System.DateTime StockEntryDate2 { get; set; }
        public int StockEntryTypeID { get; set; }
        public int StockEntryStatusID { get; set; }
        public int StockEntrySortID { get; set; }
        public int StockEntryParentID { get; set; }
        public long StockEntryLineParentID { get; set; }
        public int StockItemID { get; set; }
        public int StockItemID2 { get; set; }
        public int StockLocationID { get; set; }
        public int StockLocationID2 { get; set; }
        public double StockQuantity { get; set; }
        public double StockQuantity2 { get; set; }
        public double StockAmount { get; set; }
        public double StockAmount2 { get; set; }
        public double StockRestQuantity { get; set; }
        public double StockRestQuantity2 { get; set; }
        public double StockRestQuantity3 { get; set; }
        public int StockItemGroupID { get; set; }
        public int StockItemGroupID2 { get; set; }
        public int StockAllocationBaseID { get; set; }
        public int StockCarID { get; set; }
        public int StockPersonID { get; set; }
        public int StockDeliveryID { get; set; }
        public string TextCompanyKey { get; set; }
        public string TextCompanyName { get; set; }
        public string TextCompanyAddress { get; set; }
        public string TextStockCarKey { get; set; }
        public string TextStockCarName { get; set; }
        public string TextStockPersonKey { get; set; }
        public string TextStockPersonName { get; set; }
        public int TransCompanyID { get; set; }
        public int TransTaxMethodID { get; set; }
        public double TransTaxMethodFactor { get; set; }
        public int TransItemID { get; set; }
        public int TransItemUnitID { get; set; }
        public double TransItemUnitFactor { get; set; }
        public double TransItemUnitFactor2 { get; set; }
        public double TransQuantityInitial { get; set; }
        public double TransQuantity { get; set; }
        public int TransQuantityAllowChange { get; set; }
        public double TransPriceInitial { get; set; }
        public double TransPrice { get; set; }
        public int TransPriceAllowChange { get; set; }
        public double TransPriceOverall { get; set; }
        public int TransPriceTaxID { get; set; }
        public double TransPriceTaxFactor { get; set; }
        public double TransAmount { get; set; }
        public double TransTaxAmount { get; set; }
        public double TransBaseAmount { get; set; }
        public int TransDiscountID { get; set; }
        public double TransDiscountFactor { get; set; }
        public double TransDiscountAmount { get; set; }
        public double TransDiscountTaxAmount { get; set; }
        public double TransDiscountBaseAmount { get; set; }
        public int RSWaybillTypeID { get; set; }
        public long RSWaybillID { get; set; }
        public string RSWaybillKey { get; set; }
        public int ShellWorkTrigger { get; set; }
        public int TransItemBOMID { get; set; }
        public string TransItemKey { get; set; }
        public string TransItemName { get; set; }
        public string TransItemUnitName { get; set; }
        public string StockItemKey { get; set; }
        public string StockItemName { get; set; }
        public double TransQuantityFactor { get; set; }
        public int StockBOMPlanLineStatusID { get; set; }
        public string StockItemUnitName { get; set; }
        public int ShellCustomerID { get; set; }
        public int StockBOMPlanLineTypeID { get; set; }
        public bool StockFlag1 { get; set; }
        public bool StockFlag2 { get; set; }
        public bool StockFlag3 { get; set; }
        public double QuantityW1 { get; set; }
        public double QuantityW2 { get; set; }
        public double QuantityW3 { get; set; }
        public double QuantityW4 { get; set; }
        public double QuantityW5 { get; set; }
        public double QuantityW6 { get; set; }
        public double QuantityW7 { get; set; }
        public double QuantityW0 { get; set; }
        public double LeftDays { get; set; }
        public double MinQuantity { get; set; }
        public double MaxQuantity { get; set; }
        public double MinDays { get; set; }
        public double MaxDays { get; set; }
        public int StockDeliveryGraphID { get; set; }
        public int StockDeliveryTypeID { get; set; }
        public int StockUsageTypeID { get; set; }
        public double StockQLimitFactor { get; set; }
        public double OrderFactor { get; set; }
        public double PackQuantity { get; set; }
        public double StockQuantity3 { get; set; }
        public int TransCompanyGroupID { get; set; }
        public bool StockFlag4 { get; set; }
        public bool StockFlag5 { get; set; }
        public double OrderDays { get; set; }
        public int StockRPTypeID { get; set; }
        public double StockRestQuantity4 { get; set; }
        public double StockRestQuantity3New { get; set; }
    }
}
