//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntry21xZEdit0
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellMessageID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkStatusID_BR { get; set; }
        public int StockEntryID_R { get; set; }
        public System.DateTime ShellDateTime_FromR { get; set; }
        public Nullable<System.DateTime> ShellDateTime_ToR { get; set; }
        public string StockEntryKey_R { get; set; }
        public Nullable<int> cmdNextColumn3 { get; set; }
        public int StockCustomerID_BR { get; set; }
        public int StockLocationID_BR { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public double TransTotalAmount_R { get; set; }
        public double TransTotalTaxAmount_R { get; set; }
        public Nullable<int> cmdNextRow { get; set; }
        public double TransAmount_R { get; set; }
        public double TransServiceAmount_R { get; set; }
        public double TransDiscountAmount_R { get; set; }
        public Nullable<int> cmdNextColumn1 { get; set; }
        public double TransPayCashAmount_R { get; set; }
        public double TransPayCashChangeAmount_R { get; set; }
        public Nullable<int> cmdNextRow1 { get; set; }
        public double TransPayBankAmount_R { get; set; }
        public double TransPayInvoiceAmount_R { get; set; }
        public double TransPayOtherAmount_R { get; set; }
        public Nullable<int> cmdNextColumn2 { get; set; }
        public double StockPayPeriodOpenAmount_R { get; set; }
        public double StockPayPeriodCashAmount_R { get; set; }
        public double StockPayPeriodInAmount_R { get; set; }
        public double StockPayPeriodOutAmount_R { get; set; }
        public double StockPayPeriodDifferenceAmount_R { get; set; }
        public double StockPayPeriodCloseAmount_R { get; set; }
    }
}
