//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSupplierGroupEdit1
    {
        public int StockSupplierID { get; set; }
        public string StockSupplierKey { get; set; }
        public string StockSupplierName { get; set; }
        public int StockSupplierGroupID { get; set; }
        public int StockSupplierStatusID { get; set; }
        public int StockTaxID_C { get; set; }
        public string StockSupplierTaxNumber { get; set; }
        public string StockSupplierAddress { get; set; }
        public string StockSupplierAddress2 { get; set; }
        public string StockSupplierAddress3 { get; set; }
        public string StockSupplierPhone { get; set; }
        public string StockSupplierMail { get; set; }
        public int StockCompanyTypeID { get; set; }
        public int StockSupplierTypeID { get; set; }
    }
}
