//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemUnitTypeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockItemUnitTypeTable()
        {
            this.StockItemUnitTables = new HashSet<StockItemUnitTable>();
        }
    
        public int StockItemUnitTypeID { get; set; }
        public string StockItemUnitTypeKey { get; set; }
        public string StockItemUnitTypeName { get; set; }
        public string StockItemUnitTypeNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockItemUnitTable> StockItemUnitTables { get; set; }
    }
}
