//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPersonGroupEdit0
    {
        public int StockPersonGroupID { get; set; }
        public string StockPersonGroupKey { get; set; }
        public string StockPersonGroupName { get; set; }
    }
}
