//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntryStatusTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockEntryStatusTable()
        {
            this.StockEntryTables = new HashSet<StockEntryTable>();
        }
    
        public int StockEntryStatusID { get; set; }
        public string StockEntryStatusKey { get; set; }
        public string StockEntryStatusName { get; set; }
        public string StockEntryStatusNote { get; set; }
        public int StockR9Flag { get; set; }
        public int StockR5Flag { get; set; }
        public int StockR3Flag { get; set; }
        public int StockR2Flag { get; set; }
        public int StockR0Flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockEntryTable> StockEntryTables { get; set; }
    }
}
