//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSalesPriceGroupTable
    {
        public int StockSalesPriceGroupID { get; set; }
        public string StockSalesPriceGroupKey { get; set; }
        public string StockSalesPriceGroupName { get; set; }
        public string StockSalesPriceGroupNote { get; set; }
        public Nullable<int> StockSalesPriceGroupParentID { get; set; }
    }
}
