//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLocationEdit9
    {
        public int StockLocationBOMPlanGroupID { get; set; }
        public int StockLocationID { get; set; }
        public int StockBOMPlanGroupID_C { get; set; }
        public string StockLocationBOMPlanGroupName { get; set; }
    }
}
