//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBOMPlanGroupEdit5
    {
        public int StockBOMPlanGroupID { get; set; }
        public int StockLocationT1ID_Z { get; set; }
        public System.DateTime StockBOMPlanDate { get; set; }
        public int StockItemT3ID_C { get; set; }
        public string StockBOMPlanKey { get; set; }
        public string StockBOMPlanName { get; set; }
        public int StockLocationID { get; set; }
    }
}
