//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockCustomerGroupEdit1
    {
        public int StockCustomerID { get; set; }
        public string StockCustomerKey { get; set; }
        public string StockCustomerName { get; set; }
        public int StockCustomerGroupID { get; set; }
        public int StockCustomerStatusID { get; set; }
        public int StockTaxID_C { get; set; }
        public string StockCustomerTaxNumber { get; set; }
        public int StockTaxMethodID_C { get; set; }
        public int StockPlanningMethodID_C { get; set; }
        public string StockCustomerAddress { get; set; }
        public string StockCustomerAddress2 { get; set; }
        public string StockCustomerAddress3 { get; set; }
        public string StockCustomerPhone { get; set; }
        public string StockCustomerMail { get; set; }
        public int StockCompanyTypeID { get; set; }
    }
}
