//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBOMPlanLineStatusTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockBOMPlanLineStatusTable()
        {
            this.StockBOMPlanLineTables = new HashSet<StockBOMPlanLineTable>();
        }
    
        public int StockBOMPlanLineStatusID { get; set; }
        public string StockBOMPlanLineStatusKey { get; set; }
        public string StockBOMPlanLineStatusName { get; set; }
        public string StockBOMPlanLineStatusNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockBOMPlanLineTable> StockBOMPlanLineTables { get; set; }
    }
}
