//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockValuation00Edit1
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public int ShellMessageID_R { get; set; }
        public int ShellDataPageLinkID { get; set; }
        public int ShellDataPageLineLinkID { get; set; }
        public Nullable<int> StockItemID_FR { get; set; }
        public Nullable<int> StockLocationID_AR { get; set; }
        public Nullable<System.DateTime> StockEntryDate_R { get; set; }
        public double StockQuantity { get; set; }
        public double StockPrice { get; set; }
        public double StockAmount { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public double StockPrice1 { get; set; }
        public double StockAmount1 { get; set; }
        public Nullable<int> cmdNextColumn1 { get; set; }
        public double Amount_R { get; set; }
        public double TaxAmount_R { get; set; }
        public Nullable<int> StockEntryID { get; set; }
        public Nullable<long> StockEntryLineID { get; set; }
        public Nullable<long> StockEntryLineParentID { get; set; }
        public Nullable<int> StockEntryLineTypeID_CR { get; set; }
    }
}
