//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDeliveryEdit0
    {
        public int StockDeliveryID { get; set; }
        public string StockDeliveryKey { get; set; }
        public string StockDeliveryName { get; set; }
        public int StockDeliveryTypeID_C { get; set; }
        public int StockDeliveryStatusID_C { get; set; }
        public int StockDeliveryGroupID_C { get; set; }
    }
}
