//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockWorkBudgetTable
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID { get; set; }
        public int ShellMessageID { get; set; }
        public Nullable<System.DateTime> ShellDateFrom { get; set; }
        public Nullable<System.DateTime> ShellDateTo { get; set; }
        public Nullable<int> StockCompanyGroupID { get; set; }
        public Nullable<int> StockCompanyID { get; set; }
        public Nullable<int> StockLocationGroupID { get; set; }
        public Nullable<int> StockLocationID { get; set; }
        public Nullable<int> StockItemGroupID { get; set; }
        public Nullable<int> StockItemGroupID2 { get; set; }
        public Nullable<int> StockItemID { get; set; }
        public double StockQuantity { get; set; }
        public Nullable<int> StockEntryTypeID { get; set; }
        public Nullable<int> StockEntryLineTypeID { get; set; }
        public double Quantity01 { get; set; }
        public double Quantity02 { get; set; }
        public double Quantity03 { get; set; }
        public double Quantity04 { get; set; }
        public double Quantity05 { get; set; }
        public double Quantity06 { get; set; }
        public double Quantity07 { get; set; }
        public double Quantity08 { get; set; }
        public double Quantity09 { get; set; }
        public double Quantity10 { get; set; }
        public double Quantity11 { get; set; }
        public double Quantity12 { get; set; }
        public double Quantity13 { get; set; }
        public double Quantity14 { get; set; }
        public double Quantity15 { get; set; }
        public double Quantity16 { get; set; }
        public double Quantity17 { get; set; }
        public double Quantity18 { get; set; }
        public double Quantity19 { get; set; }
        public double Quantity20 { get; set; }
        public double Quantity21 { get; set; }
        public double Quantity22 { get; set; }
        public double Quantity23 { get; set; }
        public double Quantity24 { get; set; }
        public double Quantity25 { get; set; }
        public double Quantity26 { get; set; }
        public double Quantity27 { get; set; }
        public double Quantity28 { get; set; }
        public double Quantity29 { get; set; }
        public double Quantity30 { get; set; }
        public double Quantity31 { get; set; }
        public Nullable<int> ShellWorkPageParentID { get; set; }
        public Nullable<int> ShellWorkPageLineParentID { get; set; }
        public Nullable<int> StockBudgetTypeID { get; set; }
        public double QuantityW1 { get; set; }
        public double QuantityW2 { get; set; }
        public double QuantityW3 { get; set; }
        public double QuantityW4 { get; set; }
        public double QuantityW5 { get; set; }
        public double QuantityW6 { get; set; }
        public double QuantityW7 { get; set; }
        public double MinQuantity { get; set; }
        public double MaxQuantity { get; set; }
        public double MinDays { get; set; }
        public double MaxDays { get; set; }
        public double PackQuantity { get; set; }
        public Nullable<System.DateTime> StockEntryDate { get; set; }
        public double QuantityW0 { get; set; }
        public double LeftDays { get; set; }
        public Nullable<int> StockDeliveryGraphID { get; set; }
        public double StockQuantity2 { get; set; }
        public double Quantity32 { get; set; }
        public double Quantity33 { get; set; }
        public double Quantity34 { get; set; }
        public double Quantity35 { get; set; }
        public double Quantity36 { get; set; }
        public double Quantity37 { get; set; }
        public double Quantity38 { get; set; }
        public double Quantity39 { get; set; }
        public double Quantity40 { get; set; }
        public double Quantity41 { get; set; }
        public double Quantity42 { get; set; }
        public Nullable<int> StockDeliveryTypeID { get; set; }
        public Nullable<int> StockUsageTypeID { get; set; }
        public Nullable<int> StockEntryID { get; set; }
        public Nullable<long> StockEntryLineID { get; set; }
        public double TransQuantity { get; set; }
        public string TransItemUnitKey { get; set; }
        public double TransItemUnitFactor { get; set; }
        public double TransPrice { get; set; }
        public int TransTaxID { get; set; }
        public double TransTaxBaseFactor { get; set; }
        public double TransTaxFactor { get; set; }
        public Nullable<int> StockLocationID2 { get; set; }
        public double StockQLimitFactor { get; set; }
        public Nullable<long> StockEntryLineID2 { get; set; }
        public double OrderFactor { get; set; }
    }
}
