//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntryRP9Edit1
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public int ShellMessageID_R { get; set; }
        public int ShellDataPageLinkID { get; set; }
        public int ShellDataPageLineLinkID { get; set; }
        public int StockItemID_CR { get; set; }
        public double StockRestQuantity { get; set; }
        public double StockRestQuantity3 { get; set; }
        public double QuantityW0 { get; set; }
        public double LeftDays { get; set; }
        public double QuantityOrdered_OR { get; set; }
        public double QuantityOrdered_R { get; set; }
        public double TransQuantityInitial2_R { get; set; }
        public double TransQuantity { get; set; }
        public double QuantityWX_R { get; set; }
        public double StockDiff4Quantity_R { get; set; }
        public bool StockFlag_AR { get; set; }
        public bool FlagS_R { get; set; }
        public bool FlagD_R { get; set; }
        public bool FlagO { get; set; }
        public int StockRPTypeID_AR { get; set; }
        public int StockDeliveryTypeID_AR { get; set; }
        public int StockSupplierID_AR { get; set; }
        public int StockLocationID_AR { get; set; }
        public Nullable<int> cmdNextColumn1 { get; set; }
        public double MinQuantity_R { get; set; }
        public double MaxQuantity_R { get; set; }
        public double MinDays_R { get; set; }
        public double MaxDays_R { get; set; }
        public double OrderDays_R { get; set; }
        public double OrderFactor_R { get; set; }
        public double DMQuantity_R { get; set; }
    }
}
