//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemBOMTable
    {
        public int StockItemBOMID { get; set; }
        public string StockItemBOMKey { get; set; }
        public string StockItemBOMName { get; set; }
        public string StockItemBOMNote { get; set; }
        public int StockItemBOMTypeID { get; set; }
        public int StockItemBOMStatusID { get; set; }
        public System.DateTime StockItemBOMValidFrom { get; set; }
        public Nullable<System.DateTime> StockItemBOMValidTo { get; set; }
        public int StockItemBOMSortID { get; set; }
        public int StockItemID { get; set; }
        public int StockItemID2 { get; set; }
        public double StockItemBOMQuantity { get; set; }
        public double StockQuantity { get; set; }
    }
}
