//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPriceLineTable
    {
        public int StockPriceID { get; set; }
        public long StockPriceLineID { get; set; }
        public string StockPriceLineKey { get; set; }
        public string StockPriceLineName { get; set; }
        public int StockPriceLineSortID { get; set; }
        public int StockPriceLineSortID2 { get; set; }
        public int StockPriceLineTypeID { get; set; }
        public int StockPriceLineStatusID { get; set; }
        public System.DateTime StockPriceLineValidFrom { get; set; }
        public System.DateTime StockPriceLineValidTo { get; set; }
        public int StockCompanyID { get; set; }
        public string StockCompanyItemKey { get; set; }
        public string StockCompanyItemName { get; set; }
        public string StockCompanyItemUnitName { get; set; }
        public int StockItemID { get; set; }
        public double StockPrice { get; set; }
        public int StockPriceTaxID { get; set; }
        public double StockPriceQuantityFactor { get; set; }
        public double StockBasePrice { get; set; }
        public double StockBasePriceFactor { get; set; }
        public int StockEntryID { get; set; }
        public int StockLocationID { get; set; }
        public System.DateTime ShellCreationDate { get; set; }
        public int StockSalesItemGroupID { get; set; }
    
        public virtual StockEntryTable StockEntryTable { get; set; }
        public virtual StockPriceTable StockPriceTable { get; set; }
    }
}
