//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemT0StatusTable
    {
        public int StockItemT0StatusID { get; set; }
        public string StockItemT0StatusKey { get; set; }
        public string StockItemT0StatusName { get; set; }
        public string StockItemT0StatusNote { get; set; }
    }
}
