//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSales20Edit1
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public int ShellMessageID_R { get; set; }
        public int ShellDataPageLinkID { get; set; }
        public int ShellDataPageLineLinkID { get; set; }
        public Nullable<int> StockCustomerID_CR { get; set; }
        public Nullable<int> StockLocationID_AR { get; set; }
        public int StockItemGroupID_C { get; set; }
        public Nullable<int> StockItemID_C { get; set; }
        public double Quantity { get; set; }
        public Nullable<double> FullPrice { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public double Amount { get; set; }
        public double TaxAmount { get; set; }
        public double FullAmount { get; set; }
        public double StockAmount { get; set; }
        public Nullable<double> Total_Quantity { get; set; }
        public Nullable<double> Total_Amount { get; set; }
        public Nullable<double> Total_TaxAmount { get; set; }
        public Nullable<double> Total_FullAmount { get; set; }
        public Nullable<double> Total_StockAmount { get; set; }
    }
}
