//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemGroupTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockItemGroupTable()
        {
            this.StockItemGroupTable1 = new HashSet<StockItemGroupTable>();
            this.StockItemTables = new HashSet<StockItemTable>();
        }
    
        public int StockItemGroupID { get; set; }
        public string StockItemGroupKey { get; set; }
        public string StockItemGroupName { get; set; }
        public string StockItemGroupNote { get; set; }
        public int StockItemGroupParentID { get; set; }
        public int StockItemTypeID { get; set; }
        public int StockItemGroupSortID { get; set; }
        public int StockItemGroupDiscountID { get; set; }
        public double StockItemGroupDiscountFactor { get; set; }
        public double StockItemGroupDiscountTime { get; set; }
        public double StockItemGroupDiscountDuration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockItemGroupTable> StockItemGroupTable1 { get; set; }
        public virtual StockItemGroupTable StockItemGroupTable2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockItemTable> StockItemTables { get; set; }
    }
}
