//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBOMPlanLineTypeTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockBOMPlanLineTypeTable()
        {
            this.StockBOMPlanLineTables = new HashSet<StockBOMPlanLineTable>();
        }
    
        public int StockBOMPlanLineTypeID { get; set; }
        public string StockBOMPlanLineTypeKey { get; set; }
        public string StockBOMPlanLineTypeName { get; set; }
        public string StockBOMPlanLineTypeNote { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockBOMPlanLineTable> StockBOMPlanLineTables { get; set; }
    }
}
