//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntry2130Edit2
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellMessageID_R { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public Nullable<int> ShellWorkPageParentID { get; set; }
        public Nullable<int> ShellWorkPageLineParentID { get; set; }
        public int StockSalesItemID { get; set; }
        public string StockItemName_R { get; set; }
        public Nullable<int> StockWork2130_QuantityFactorDecrease { get; set; }
        public double TransQuantityFactor_R { get; set; }
        public Nullable<int> StockWork2130_QuantityFactorIncrease { get; set; }
        public string StockEntryName { get; set; }
    }
}
