//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemT5StatusTable
    {
        public int StockItemT5StatusID { get; set; }
        public string StockItemT5StatusKey { get; set; }
        public string StockItemT5StatusName { get; set; }
        public string StockItemT5StatusNote { get; set; }
    }
}
