//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockCompanyCardStatusTable
    {
        public int StockCompanyCardStatusID { get; set; }
        public string StockCompanyCardStatusKey { get; set; }
        public string StockCompanyCardStatusName { get; set; }
        public string StockCompanyCardStatusNote { get; set; }
    }
}
