//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSalesItemList
    {
        public int StockSalesItemID { get; set; }
        public string StockSalesItemKey { get; set; }
        public string StockSalesItemName { get; set; }
        public int StockSalesItemTypeID { get; set; }
        public int StockSalesItemStatusID { get; set; }
        public int StockSalesItemGroupID { get; set; }
        public Nullable<double> StockSalesPrice { get; set; }
    }
}
