//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntryRP9Edit0
    {
        public int ShellMessageID_R { get; set; }
        public int ShellWorkStatusID_B { get; set; }
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public string StockEntryKey { get; set; }
        public string StockEntryName { get; set; }
        public System.DateTime StockEntryDate { get; set; }
        public System.DateTime StockEntryDate_SO { get; set; }
        public double QuantityWeek { get; set; }
        public double QuantityWeekMiss { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public int StockLocationID_CZ { get; set; }
    }
}
