//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockDiscountGroupEdit5
    {
        public int StockDiscountID { get; set; }
        public string StockDiscountKey { get; set; }
        public string StockDiscountName { get; set; }
        public int StockDiscountTypeID_C { get; set; }
        public int StockDiscountGroupID { get; set; }
    }
}
