//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntryP50Edit1
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellMessageID_R { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public int StockItemT0ID_CR { get; set; }
        public double Quantity { get; set; }
        public double TransItemUnitFactor_R { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public int StockAllowChange_R { get; set; }
        public double TransPrice_R { get; set; }
        public double FullPrice { get; set; }
        public int StockTaxID_CR { get; set; }
        public double TotalAmount_R { get; set; }
        public Nullable<int> cmdNextColumn2 { get; set; }
        public int StockItemT1ID_CR { get; set; }
        public double StockQuantity_R { get; set; }
        public double StockRestQuantity { get; set; }
        public double StockRestQuantity2 { get; set; }
        public double StockRestQuantity3 { get; set; }
    }
}
