//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLiveEntry00Edit3
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public int ShellMessageID_R { get; set; }
        public int ShellDataPageLinkID { get; set; }
        public int ShellDataPageLineLinkID { get; set; }
        public Nullable<int> StockItemID_C { get; set; }
        public double Quantity { get; set; }
        public double FCPrice { get; set; }
        public Nullable<int> StockTaxID_C { get; set; }
        public double Amount_R { get; set; }
        public double TaxAmount_R { get; set; }
        public double FullAmount_R { get; set; }
        public Nullable<int> StockEntryLineSortID_R { get; set; }
        public Nullable<int> StockLocationID_CR { get; set; }
        public Nullable<int> StockEntryLineTypeID_CR { get; set; }
    }
}
