//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntryP10Table
    {
        public int StockEntryP10ID { get; set; }
        public string StockEntryP10Key { get; set; }
        public string StockEntryP10Name { get; set; }
        public Nullable<int> StockEntryP10GroupID { get; set; }
        public Nullable<int> cmdVoidEntry { get; set; }
        public System.DateTime StockEntryDate { get; set; }
        public int StockLocationID_A { get; set; }
        public double TransTotalAmount { get; set; }
        public double TransTotalTaxAmount { get; set; }
        public int StockCompanyID_C { get; set; }
    }
}
