//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntryDP9Edit1
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID_R { get; set; }
        public int ShellMessageID_R { get; set; }
        public int ShellDataPageLinkID { get; set; }
        public int ShellDataPageLineLinkID { get; set; }
        public int StockCustomerID_C { get; set; }
        public int StockItemID_CR { get; set; }
        public double TransQuantity { get; set; }
        public string StockEntryKey_R { get; set; }
        public Nullable<int> StockEntryID_R { get; set; }
        public long StockEntryLineID { get; set; }
        public int StockLocationID_CR { get; set; }
        public int StockCompanyGroupID_CR { get; set; }
    }
}
