//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockEntrySP9Edit0
    {
        public int ShellMessageID_R { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkStatusID_B { get; set; }
        public Nullable<int> StockEntryID_R { get; set; }
        public System.DateTime ShellDateFrom { get; set; }
        public System.DateTime ShellDateTo { get; set; }
        public string StockEntryKey_R { get; set; }
        public string StockEntryName { get; set; }
        public int StockLocationID_CZ { get; set; }
        public int StockAssociateCustomerID_CR { get; set; }
        public int StockCustomerID_C { get; set; }
        public int StockPersonID_C { get; set; }
    }
}
