//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemT0TypeTable
    {
        public int StockItemT0TypeID { get; set; }
        public string StockItemT0TypeKey { get; set; }
        public string StockItemT0TypeName { get; set; }
        public string StockItemT0TypeNote { get; set; }
    }
}
