//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSupplierEdit1
    {
        public long StockPriceLineID { get; set; }
        public int StockPriceID { get; set; }
        public int StockPriceLineSortID { get; set; }
        public int StockSupplierID { get; set; }
        public int StockItemID_C { get; set; }
        public double StockPrice { get; set; }
        public int StockTaxID_C { get; set; }
        public double TransQuantityFactor { get; set; }
        public int StockPriceLineTypeID_C { get; set; }
        public int StockPriceLineStatusID_C { get; set; }
        public System.DateTime StockPriceLineValidFrom { get; set; }
        public System.DateTime StockPriceLineValidTo { get; set; }
        public string StockCompanyItemKey { get; set; }
        public string StockCompanyItemName { get; set; }
        public string StockCompanyItemUnitName { get; set; }
        public string StockPriceLineItemSortID { get; set; }
    }
}
