//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLiveEntry00Edit1
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellMessageID { get; set; }
        public int ShellDataPageLinkID { get; set; }
        public int ShellDataPageLineLinkID { get; set; }
        public Nullable<int> StockEntryID { get; set; }
        public Nullable<int> StockEntryTypeID_CR { get; set; }
        public Nullable<int> StockEntryStatusID_CR { get; set; }
        public string StockEntryKey { get; set; }
        public string StockEntryName { get; set; }
        public Nullable<int> StockEntryID2 { get; set; }
        public Nullable<int> ShellUserID_CR { get; set; }
        public Nullable<int> cmdNextColumn { get; set; }
        public Nullable<System.DateTime> StockEntryDate { get; set; }
        public Nullable<System.DateTime> StockEntryDate2_R { get; set; }
        public Nullable<int> StockLocationID_CR { get; set; }
        public Nullable<int> StockCompanyID_CR { get; set; }
        public Nullable<int> StockPersonID_C { get; set; }
        public Nullable<int> StockCarID_C { get; set; }
        public Nullable<int> cmdNextRow { get; set; }
        public double Amount_R { get; set; }
        public double TaxAmount_R { get; set; }
        public double FullAmount_R { get; set; }
    }
}
