//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockBalance00Edit8
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public Nullable<int> ShellWorkPageLineID_R { get; set; }
        public int ShellDataPageLinkID { get; set; }
        public Nullable<int> ShellDataPageLineLinkID { get; set; }
        public Nullable<int> StockItemID_CR { get; set; }
    }
}
