//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTaxMethodTable
    {
        public int StockTaxMethodID { get; set; }
        public string StockTaxMethodKey { get; set; }
        public string StockTaxMethodName { get; set; }
        public string StockTaxMethodNote { get; set; }
        public int StockTaxMethodStatusID { get; set; }
        public double StockTaxMethodFactor { get; set; }
    }
}
