//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockItemT3List
    {
        public int StockItemT3ID { get; set; }
        public string StockItemT3Key { get; set; }
        public string StockItemT3Name { get; set; }
        public int StockItemTypeID { get; set; }
        public int StockItemT3StatusID { get; set; }
        public int StockItemT3GroupID { get; set; }
        public int StockItemUnitID_C { get; set; }
        public int StockTaxID_C { get; set; }
        public int StockItemValidDays { get; set; }
        public string StockItemT1Key { get; set; }
        public string StockItemT1Name { get; set; }
        public string StockItemUnitName { get; set; }
        public double StockQuantity2 { get; set; }
        public double StockItemProtein { get; set; }
        public double StockItemFat { get; set; }
        public double StockItemCarbohydrate { get; set; }
        public double StockItemCalorie { get; set; }
    }
}
