//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockCompanyTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StockCompanyTable()
        {
            this.StockEntryTables = new HashSet<StockEntryTable>();
            this.StockEntryTables1 = new HashSet<StockEntryTable>();
            this.StockLocationAddressTables = new HashSet<StockLocationAddressTable>();
            this.StockSalesItemGroupNameTables = new HashSet<StockSalesItemGroupNameTable>();
        }
    
        public int StockCompanyID { get; set; }
        public string StockCompanyKey { get; set; }
        public string StockCompanyName { get; set; }
        public string StockCompanyNote { get; set; }
        public int StockCompanySortID { get; set; }
        public int StockCompanyTypeID { get; set; }
        public int StockCompanyStatusID { get; set; }
        public int StockCompanyGroupID { get; set; }
        public int StockPriceID { get; set; }
        public int StockTaxID { get; set; }
        public int StockTaxMethodID { get; set; }
        public double StockCompanyDiscountFactor { get; set; }
        public string StockCompanyAddress { get; set; }
        public string StockCompanyAddress2 { get; set; }
        public string StockCompanyAddress3 { get; set; }
        public string StockCompanyPhone { get; set; }
        public string StockCompanyFax { get; set; }
        public string StockCompanyMail { get; set; }
        public string StockCompanyWeb { get; set; }
        public string StockCompanyCountry { get; set; }
        public string StockCompanyTaxNumber { get; set; }
        public string StockCompanyBankCode { get; set; }
        public string StockCompanyBankName { get; set; }
        public string StockCompanyBankAccount { get; set; }
        public int StockCompanyParentID { get; set; }
        public int StockCompanyFlag { get; set; }
        public int StockPlanningMethodID { get; set; }
    
        public virtual StockCompanyGroupTable StockCompanyGroupTable { get; set; }
        public virtual StockCompanyStatusTable StockCompanyStatusTable { get; set; }
        public virtual StockCompanyTypeTable StockCompanyTypeTable { get; set; }
        public virtual StockPriceTable StockPriceTable { get; set; }
        public virtual StockTaxTable StockTaxTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockEntryTable> StockEntryTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockEntryTable> StockEntryTables1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockLocationAddressTable> StockLocationAddressTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockSalesItemGroupNameTable> StockSalesItemGroupNameTables { get; set; }
    }
}
