//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransItemGroupEdit0
    {
        public int TransItemGroupID { get; set; }
        public string TransItemGroupKey { get; set; }
        public string TransItemGroupName { get; set; }
        public int StockItemGroupParentID_H { get; set; }
        public int StockItemTypeID { get; set; }
    }
}
