//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransItemStatusTable
    {
        public int TransItemStatusID { get; set; }
        public string TransItemStatusKey { get; set; }
        public string TransItemStatusName { get; set; }
        public string TransItemStatusNote { get; set; }
    }
}
