//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zPOSWorkTable
    {
        public int ShellUserID { get; set; }
        public int ShellOperationID { get; set; }
        public int ShellWorkPageID { get; set; }
        public int ShellWorkPageLineID { get; set; }
        public Nullable<int> ShellWorkPageParentID { get; set; }
        public Nullable<int> ShellWorkPageLineParentID { get; set; }
        public double ShellWorkPageSign { get; set; }
        public int ShellWorkPageAuto { get; set; }
        public int ShellMessageID { get; set; }
        public int ShellWorkStatusID { get; set; }
        public Nullable<int> StockEntryID { get; set; }
        public Nullable<long> StockEntryLineID { get; set; }
        public string StockEntryKey { get; set; }
        public string StockEntryName { get; set; }
        public Nullable<System.DateTime> StockEntryDate { get; set; }
        public Nullable<System.DateTime> StockEntryDateInitial { get; set; }
        public Nullable<int> StockEntryTypeID { get; set; }
        public Nullable<int> StockEntryStatusID { get; set; }
        public Nullable<int> StockEntryParentID { get; set; }
        public Nullable<long> StockEntryLineParentID { get; set; }
        public Nullable<int> TransCompanyID { get; set; }
        public int TransCurrencyID { get; set; }
        public double TransCurrencyFactor { get; set; }
        public int TransTaxMethodID { get; set; }
        public double TransTaxMethodFactor { get; set; }
        public Nullable<int> TransItemID { get; set; }
        public Nullable<int> TransItemUnitID { get; set; }
        public double TransItemUnitFactor { get; set; }
        public double TransQuantity { get; set; }
        public double TransPrice { get; set; }
        public double TransPriceOverall { get; set; }
        public double TransPriceAmount { get; set; }
        public int TransTaxID { get; set; }
        public double TransTaxBaseFactor { get; set; }
        public double TransTaxFactor { get; set; }
        public double TransTaxBaseAmount { get; set; }
        public double TransTaxAmount { get; set; }
        public double TransTotalAmount { get; set; }
        public int TransPayMethodID { get; set; }
        public int TransPayDiscountID { get; set; }
        public double TransPayDiscountRate { get; set; }
        public double TransPayDiscountAmount { get; set; }
        public double TransToPayAmount { get; set; }
        public double TransPaidTotalAmount { get; set; }
        public Nullable<int> StockLocationID { get; set; }
        public Nullable<int> StockItemID { get; set; }
        public Nullable<int> StockItemUnitID { get; set; }
        public double StockQuantity { get; set; }
        public double StockAmount { get; set; }
        public double StockTaxBaseAmount { get; set; }
        public double StockTaxAmount { get; set; }
        public double StockTotalAmount { get; set; }
        public double StockPayDiscountAmount { get; set; }
        public double StockToPayAmount { get; set; }
        public double StockPaidTotalAmount { get; set; }
        public Nullable<System.DateTime> ShellCreationDate { get; set; }
        public Nullable<System.DateTime> ShellModificationDate { get; set; }
        public Nullable<int> ShellCreatorUserID { get; set; }
        public Nullable<int> ShellModifierUserID { get; set; }
        public double StockRestQuantity { get; set; }
        public double StockRestAmount { get; set; }
        public double StockRestPrice { get; set; }
        public double StockRestQuantity2 { get; set; }
        public double StockRestQuantity3 { get; set; }
        public double TransQuantityInitial { get; set; }
        public Nullable<int> ShellComputerID { get; set; }
        public double TransCommissionAmount { get; set; }
        public string Comment { get; set; }
        public bool ShellFlag1 { get; set; }
        public bool ShellFlag2 { get; set; }
        public bool ShellFlag3 { get; set; }
        public bool ShellFlag4 { get; set; }
        public int TransPayPeriodID { get; set; }
        public double TransBaseAmount { get; set; }
        public double TransAmount { get; set; }
        public double TransDiscountAmount { get; set; }
        public double TransDiscountTaxAmount { get; set; }
        public double TransFiscalAmount { get; set; }
        public double TransPayAmount { get; set; }
        public double TransPayChangeAmount { get; set; }
        public double TransPayCashAmount { get; set; }
        public double TransPayBankAmount { get; set; }
        public double TransPayInvoiceAmount { get; set; }
        public double TransPayOtherAmount { get; set; }
    }
}
