//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGrid.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zShellSyncStatusTable
    {
        public int ShellSyncStatusID { get; set; }
        public string ShellSyncStatusKey { get; set; }
        public string ShellSyncStatusName { get; set; }
        public string ShellSyncStatusNote { get; set; }
    }
}
